Repository ApplETS/Notre-Dame, pull requests merged in 2021-11, with the labels that each got.

#283 Updater new version
  analysis_options.yaml
  lib/core/constants/preferences_flags.dart
  lib/core/constants/update_code.dart
  lib/core/managers/settings_manager.dart
  lib/core/services/github_api.dart
  lib/core/services/navigation_service.dart
  lib/core/services/siren_flutter_service.dart
  lib/core/viewmodels/dashboard_viewmodel.dart
  lib/core/viewmodels/startup_viewmodel.dart
  lib/l10n/intl_en.arb
  lib/l10n/intl_fr.arb
  lib/locator.dart
  lib/ui/router.dart
  lib/ui/views/dashboard_view.dart
  lib/ui/views/startup_view.dart
  pubspec.lock
  pubspec.yaml
  test/helpers.dart
  test/mock/services/siren_flutter_service_mock.dart
  test/viewmodels/startup_viewmodel_test.dart
Labels: enhancement, hacktoberfest-accepted, platform: ios, platform: android, feature: What's new, priority: medium, size: M

#268 removed false crashlytics message
  lib/core/viewmodels/web_link_card_viewmodel.dart
  pubspec.yaml
Labels: bug, good first issue, hacktoberfest-accepted, platform: ios, platform: android, size: XS

#252 Update gradle plugin
  .gitignore
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  pubspec.lock
  pubspec.yaml
Labels: enhancement, good first issue, hacktoberfest-accepted, platform: android, size: S

#286 Modified procedure to extract env variables and decrypt files
  README.fr.md
  README.md
Labels: documentation, size: XS

#292 Unify refresh behaviour for Schedule View
  lib/ui/views/schedule_view.dart
  pubspec.yaml
  test/ui/views/goldenFiles/scheduleView_1.png
  test/ui/views/goldenFiles/scheduleView_2.png
  test/ui/views/goldenFiles/scheduleView_3.png
  test/ui/views/goldenFiles/scheduleView_4.png
  test/ui/views/goldenFiles/scheduleView_5.png
Labels: size: XS

#306 Add course acronym
  .github/workflows/main-workflow.yaml
  lib/ui/widgets/schedule_settings.dart
  pubspec.yaml
  test/ui/widgets/goldenFiles/scheduleSettingsView_1.png
Labels: enhancement, platform: ios, platform: android, size: XS

#310 fix signets certificate error
  lib/core/services/signets_api.dart
  pubspec.yaml
Labels: size: XS
