Repository ApplETS/Notre-Dame, pull requests merged in 2021-03, with the labels that each got.

#47 [Grade] Backend of the feature
  android/app/build.gradle
  lib/core/constants/urls.dart
  lib/core/managers/course_repository.dart
  lib/core/models/course.dart
  lib/core/models/course_summary.dart
  lib/core/models/evaluation.dart
  lib/core/services/signets_api.dart
  lib/ui/utils/app_theme.dart
  lib/ui/views/grades_view.dart
  lib/ui/views/login_view.dart
  lib/ui/views/schedule_view.dart
  lib/ui/widgets/grade_button.dart
  lib/ui/widgets/session_widget.dart
  test/managers/course_repository_test.dart
  test/mock/services/signets_api_mock.dart
  test/services/signets_api_test.dart
  test/ui/views/goldenFiles/scheduleView_1.png
  test/ui/views/goldenFiles/scheduleView_2.png
  test/ui/views/goldenFiles/scheduleView_3.png
  test/ui/views/goldenFiles/scheduleView_4.png
  test/ui/views/goldenFiles/scheduleView_5.png
Labels: enhancement

#57 Bugfix/intl remove generated file and clean the code! Intl is now working again
  .github/workflows/validate_pr.yaml
  README.fr.md
  README.md
  ios/Runner/Info.plist
  l10n.yaml
  lib/core/constants/emergency_procedures.dart
  lib/core/constants/markers.dart
  lib/core/constants/quick_links.dart
  lib/core/managers/settings_manager.dart
  lib/core/utils/utils.dart
  lib/core/viewmodels/emergency_viewmodel.dart
  lib/core/viewmodels/login_viewmodel.dart
  lib/core/viewmodels/more_viewmodel.dart
  lib/core/viewmodels/profile_viewmodel.dart
  lib/core/viewmodels/quick_links_viewmodel.dart
  lib/core/viewmodels/schedule_viewmodel.dart
  lib/core/viewmodels/security_viewmodel.dart
  lib/core/viewmodels/settings_viewmodel.dart
  lib/generated/intl/messages_all.dart
  lib/generated/intl/messages_en.dart
  lib/generated/intl/messages_fr.dart
  lib/generated/l10n.dart
  lib/l10n/intl_fr.arb
  lib/main.dart
  lib/ui/views/about_view.dart
  lib/ui/views/contributors_view.dart
  lib/ui/views/emergency_view.dart
  lib/ui/views/login_view.dart
  lib/ui/views/more_view.dart
  lib/ui/views/profile_view.dart
  lib/ui/views/quick_links_view.dart
  lib/ui/views/schedule_view.dart
  lib/ui/views/security_view.dart
  lib/ui/views/settings_view.dart
  lib/ui/views/student_view.dart
  lib/ui/widgets/bottom_bar.dart
  lib/ui/widgets/password_text_field.dart
  lib/ui/widgets/schedule_settings.dart
  lib/ui/widgets/student_program.dart
  pubspec.lock
  pubspec.yaml
  test/helpers.dart
  test/ui/views/login_view_test.dart
  test/ui/views/more_view_test.dart
  test/ui/views/profile_view_test.dart
  test/ui/views/security_view_test.dart
  test/ui/views/settings_view_test.dart
  test/ui/widgets/password_text_field_test.dart
  test/ui/widgets/schedule_settings_test.dart
  test/ui/widgets/student_program_test.dart
  test/viewmodels/login_viewmodel_test.dart
  test/viewmodels/profile_viewmodel_test.dart
  test/viewmodels/schedule_viewmodel_test.dart
  test/viewmodels/settings_viewmodel_test.dart
Labels: bug, platform: android, platform: ios

#62 Bugfix - Schedule isn't displayed if there is no activities available
  lib/core/constants/signets_errors.dart
  lib/core/services/signets_api.dart
  test/services/signets_api_test.dart
Labels: bug, platform: android, platform: ios

#59 Feature/quicklink rubiks
  assets/images/ic_schedule_generator_red.png
  lib/core/constants/quick_links.dart
  lib/l10n/intl_en.arb
  lib/l10n/intl_fr.arb
Labels: enhancement, platform: android, platform: ios

#58 Feature/splash screen
  android/app/src/main/res/drawable-night/ets_red_logo.png
  android/app/src/main/res/drawable-night/launch_background.xml
  android/app/src/main/res/drawable/ets_white_logo.png
  android/app/src/main/res/drawable/launch_background.xml
  android/app/src/main/res/values/colors.xml
  assets/images/ets_red_logo.png
  ios/Runner/Assets.xcassets/Color.colorset/Contents.json
  ios/Runner/Assets.xcassets/Contents.json
  ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/ets_red_logo-1.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/ets_red_logo-2.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/ets_red_logo.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/ets_white_logo.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/ets_white_logo@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/ets_white_logo@3x.png
  ios/Runner/Base.lproj/LaunchScreen.storyboard
  lib/core/viewmodels/login_viewmodel.dart
  lib/ui/views/login_view.dart
  lib/ui/views/startup_view.dart
  lib/ui/widgets/password_text_field.dart
  pubspec.yaml
  test/viewmodels/login_viewmodel_test.dart
  test/viewmodels/startup_viewmodel_test.dart
Labels: enhancement, platform: android, platform: ios

#63 Not found page
  .gitignore
  assets/animations/dot_jumping.riv
  lib/core/services/rive_animation_service.dart
  lib/core/utils/animation_exception.dart
  lib/core/viewmodels/not_found_viewmodel.dart
  lib/l10n/intl_en.arb
  lib/l10n/intl_fr.arb
  lib/locator.dart
  lib/ui/router.dart
  lib/ui/views/not_found_view.dart
  lib/ui/views/startup_view.dart
  pubspec.lock
  pubspec.yaml
  test/helpers.dart
  test/mock/services/rive_animation_service_mock.dart
  test/ui/views/goldenFiles/notFoundView_1.png
  test/ui/views/not_found_view_test.dart
  test/viewmodels/not_found_viewmodel_test.dart
Labels: enhancement, platform: android, platform: ios

#70 Remove blue color for emergency procedures
  lib/ui/views/security_view.dart
  test/ui/views/security_view_test.dart
Labels: bug, platform: android, platform: ios

#66 core functionalities for the discovery feature
  lib/core/constants/discovery_components.dart
  lib/core/constants/preferences_flags.dart
  lib/core/models/discovery.dart
  lib/core/viewmodels/login_viewmodel.dart
  lib/l10n/intl_en.arb
  lib/l10n/intl_fr.arb
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, platform: android, platform: ios
