Repository ApplETS/Notre-Dame, pull requests merged in 2021-04, with the labels that each got.

#72 added env variable
  .env.template
  .gitignore
  README.fr.md
  README.md
  android/app/build.gradle
  ios/Runner/AppDelegate.swift
  lib/core/viewmodels/more_viewmodel.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, platform: android, platform: ios

#67 Feature/discovery/choose language modal
  lib/core/constants/preferences_flags.dart
  lib/core/constants/router_paths.dart
  lib/core/viewmodels/choose_language_viewmodel.dart
  lib/core/viewmodels/login_viewmodel.dart
  lib/core/viewmodels/startup_viewmodel.dart
  lib/l10n/intl_en.arb
  lib/l10n/intl_fr.arb
  lib/ui/router.dart
  lib/ui/views/choose_language_view.dart
  lib/ui/views/more_view.dart
  package-lock.json
  pubspec.yaml
  test/ui/views/choose_language_view_test.dart
  test/ui/views/goldenFiles/chooseLanguageView_1.png
  test/ui/views/login_view_test.dart
  test/viewmodels/choose_language_viewmodel_test.dart
  test/viewmodels/startup_viewmodel_test.dart
Labels: enhancement, platform: android, platform: ios

#90 Fix calendar locale and typo.
  lib/core/viewmodels/schedule_viewmodel.dart
  lib/l10n/intl_fr.arb
  lib/ui/views/schedule_view.dart
  test/mock/managers/settings_manager_mock.dart
  test/ui/views/schedule_view_test.dart
Labels: bug, platform: android, platform: ios

#64 Bugfix/theme and locale
  README.fr.md
  README.md
  docs/images/intellij_config.png
  lib/core/managers/settings_manager.dart
  lib/core/services/analytics_service.dart
  lib/core/services/github_api.dart
  lib/core/services/preferences_service.dart
  lib/core/viewmodels/more_viewmodel.dart
  lib/core/viewmodels/settings_viewmodel.dart
  lib/locator.dart
  lib/main.dart
  lib/ui/views/more_view.dart
  lib/ui/views/settings_view.dart
  test/helpers.dart
  test/managers/settings_manager_test.dart
  test/mock/managers/cache_manager_mock.dart
  test/mock/managers/user_repository_mock.dart
  test/mock/services/github_api_mock.dart
  test/services/preferences_service_test.dart
  test/ui/views/goldenFiles/settingsView_1.png
  test/ui/views/more_view_test.dart
  test/ui/views/settings_view_test.dart
  test/viewmodels/more_viewmodel_test.dart
  test/viewmodels/settings_viewmodel_test.dart
Labels: bug, platform: android, platform: ios

#99 Change image color for quick links
  lib/ui/widgets/web_link_card.dart
Labels: feature: ÉTS, platform: android, platform: ios

#102 Web link cards
  lib/ui/widgets/web_link_card.dart
Labels: bug, feature: ÉTS, platform: android, platform: ios

#100 Update dependencies and multiple fixes
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-night/ets_logo.png
  android/app/src/main/res/drawable-night/launch_background.xml
  android/app/src/main/res/drawable-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable/ets_logo.png
  android/app/src/main/res/drawable/launch_background.xml
  android/app/src/main/res/values/colors.xml
  assets/icons/ic_launcher_foreground.png
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/Contents.json
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/LaunchImage-1024x1024@1x.png
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/LaunchImage-20x20@1x.png
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/LaunchImage-20x20@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/LaunchImage-20x20@3x.png
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/LaunchImage-29x29@1x.png
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/LaunchImage-29x29@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/LaunchImage-29x29@3x.png
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/LaunchImage-40x40@1x.png
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/LaunchImage-40x40@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/LaunchImage-40x40@3x.png
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/LaunchImage-60x60@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/LaunchImage-60x60@3x.png
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/LaunchImage-76x76@1x.png
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/LaunchImage-76x76@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.appiconset/LaunchImage-83.5x83.5@2x.png
  ios/Runner/Assets.xcassets/SplashImage.imageset/Contents.json
  ios/Runner/Assets.xcassets/SplashImage.imageset/README.md
  ios/Runner/Assets.xcassets/SplashImage.imageset/ets_red_logo-1.png
  ios/Runner/Assets.xcassets/SplashImage.imageset/ets_red_logo-2.png
  ios/Runner/Assets.xcassets/SplashImage.imageset/ets_red_logo.png
  ios/Runner/Assets.xcassets/SplashImage.imageset/ets_white_logo.png
  ios/Runner/Assets.xcassets/SplashImage.imageset/ets_white_logo@2x.png
  ios/Runner/Assets.xcassets/SplashImage.imageset/ets_white_logo@3x.png
  ios/Runner/Assets.xcassets/launcher_icon.appiconset/Contents.json
  ios/Runner/Assets.xcassets/launcher_icon.appiconset/launcher_icon-50x50@1x.png
  ios/Runner/Assets.xcassets/launcher_icon.appiconset/launcher_icon-50x50@2x.png
  ios/Runner/Assets.xcassets/launcher_icon.appiconset/launcher_icon-57x57@1x.png
  ios/Runner/Assets.xcassets/launcher_icon.appiconset/launcher_icon-57x57@2x.png
  ios/Runner/Assets.xcassets/launcher_icon.appiconset/launcher_icon-72x72@1x.png
  ios/Runner/Assets.xcassets/launcher_icon.appiconset/launcher_icon-72x72@2x.png
  ios/Runner/Base.lproj/LaunchScreen.storyboard
  ios/Runner/Base.lproj/Main.storyboard
  ios/Runner/Info.plist
  lib/core/managers/settings_manager.dart
  lib/core/services/mon_ets_api.dart
  lib/core/services/rive_animation_service.dart
  lib/core/services/signets_api.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
  test/managers/settings_manager_test.dart
  test/mock/services/http_client_mock.dart
Labels: bug, platform: android, platform: ios

#103 Make text fit in grade buttons
  lib/ui/widgets/grade_button.dart
  test/ui/views/goldenFiles/gradesView_2.png
Labels: bug, feature: Grades, platform: android, platform: ios

#105 Feature/progress bar profile
  lib/core/viewmodels/profile_viewmodel.dart
  lib/ui/views/profile_view.dart
  lib/ui/widgets/student_program.dart
  test/viewmodels/profile_viewmodel_test.dart
Labels: feature: Profile, platform: android, platform: ios

#104 feature/refresh-schedule : added refresh FAB
  lib/core/viewmodels/schedule_viewmodel.dart
  lib/ui/views/schedule_view.dart
  lib/ui/widgets/base_scaffold.dart
  test/ui/views/goldenFiles/scheduleView_1.png
  test/ui/views/goldenFiles/scheduleView_2.png
  test/ui/views/goldenFiles/scheduleView_3.png
  test/ui/views/goldenFiles/scheduleView_4.png
  test/ui/views/goldenFiles/scheduleView_5.png
  test/viewmodels/schedule_viewmodel_test.dart
Labels: enhancement, feature: Schedule, platform: android, platform: ios

#109 Fix locale error when log out then log in.
  lib/core/managers/settings_manager.dart
  lib/main.dart
  test/managers/settings_manager_test.dart
Labels: bug, feature: Schedule, platform: android, platform: ios
