Repository ApplETS/Notre-Dame, pull requests merged in 2021-07, with the labels that each got.

#163 Bugfix/overscroll color
  lib/core/managers/course_repository.dart
  lib/ui/utils/app_theme.dart
  lib/ui/views/dashboard_view.dart
  lib/ui/widgets/dismissible_card.dart
  lib/ui/widgets/grade_circular_progress.dart
  pubspec.yaml
  test/ui/widgets/dismissible_card_test.dart
Labels: bug, platform: android, platform: ios

#168 Overlay in schedule settings
  lib/core/utils/utils.dart
  lib/ui/utils/app_theme.dart
  lib/ui/views/choose_language_view.dart
  lib/ui/views/login_view.dart
  lib/ui/views/startup_view.dart
  lib/ui/widgets/grade_evaluation_tile.dart
  lib/ui/widgets/schedule_settings.dart
  pubspec.yaml
Labels: bug, feature: Schedule, platform: android, platform: ios

#155 Bugfix/offline dashboard grades
  lib/core/managers/course_repository.dart
  lib/core/services/networking_service.dart
  lib/core/utils/utils.dart
  lib/core/viewmodels/grades_viewmodel.dart
  lib/core/viewmodels/profile_viewmodel.dart
  lib/core/viewmodels/schedule_viewmodel.dart
  lib/ui/widgets/base_scaffold.dart
  lib/ui/widgets/bottom_bar.dart
  pubspec.lock
  pubspec.yaml
  test/managers/course_repository_test.dart
  test/ui/views/dashboard_view_test.dart
  test/ui/views/goldenFiles/dashboardView_appletsCard_1.png
  test/ui/views/goldenFiles/dashboardView_progressBarCard_1.png
  test/ui/views/goldenFiles/dashboardView_scheduleCard_1.png
  test/ui/views/goldenFiles/gradesDetailsView_1.png
  test/ui/views/goldenFiles/gradesDetailsView_2.png
  test/ui/views/goldenFiles/moreView_1.png
  test/ui/views/goldenFiles/quicksLinksView_1.png
  test/ui/views/goldenFiles/scheduleView_1.png
  test/ui/views/goldenFiles/scheduleView_2.png
  test/ui/views/goldenFiles/scheduleView_3.png
  test/ui/views/goldenFiles/scheduleView_4.png
  test/ui/views/goldenFiles/scheduleView_5.png
  test/ui/views/goldenFiles/settingsView_1.png
  test/ui/views/goldenFiles/studentView_1.png
  test/ui/views/grades_details_view_test.dart
  test/ui/views/grades_view_test.dart
  test/ui/views/more_view_test.dart
  test/ui/views/profile_view_test.dart
  test/ui/views/quick_links_view_test.dart
  test/ui/views/schedule_view_test.dart
  test/ui/views/settings_view_test.dart
  test/ui/views/student_view_test.dart
  test/ui/widgets/base_scaffold_test.dart
  test/ui/widgets/bottom_bar_test.dart
  test/viewmodels/grades_viewmodel_test.dart
  test/viewmodels/profile_viewmodel_test.dart
  test/viewmodels/schedule_viewmodel_test.dart
Labels: bug
