Repository ApplETS/Notre-Dame, pull requests merged in 2022-05, with the labels that each got.

#350 Feature/rating
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/constants/preferences_flags.dart
  lib/core/services/in_app_review_service.dart
  lib/core/services/preferences_service.dart
  lib/core/viewmodels/dashboard_viewmodel.dart
  lib/core/viewmodels/login_viewmodel.dart
  lib/core/viewmodels/more_viewmodel.dart
  lib/locator.dart
  lib/ui/views/dashboard_view.dart
  lib/ui/views/more_view.dart
  pubspec.lock
  pubspec.yaml
  test/helpers.dart
  test/mock/services/in_app_review_service_mock.dart
  test/mock/services/preferences_service_mock.dart
  test/services/preferences_service_test.dart
  test/ui/views/dashboard_view_test.dart
  test/ui/views/goldenFiles/moreView_1.png
  test/ui/views/grades_view_test.dart
  test/ui/views/login_view_test.dart
  test/ui/views/more_view_test.dart
  test/ui/views/schedule_view_test.dart
  test/viewmodels/dashboard_viewmodel_test.dart
  test/viewmodels/login_viewmodel_test.dart
  test/viewmodels/more_viewmodel_test.dart
Labels: enhancement, platform: ios, platform: android, size: M

#439 iOS home screen widgets
  .gitignore
  ios/ETSMobile Widget/Assets.xcassets/AccentColor.colorset/Contents.json
  ios/ETSMobile Widget/Assets.xcassets/BackgroundColor-1.colorset/Contents.json
  ios/ETSMobile Widget/Assets.xcassets/BackgroundColor.colorset/Contents.json
  ios/ETSMobile Widget/Assets.xcassets/Contents.json
  ios/ETSMobile Widget/Assets.xcassets/DividerColor.colorset/Contents.json
  ios/ETSMobile Widget/Assets.xcassets/ETSLightRed.colorset/Contents.json
  ios/ETSMobile Widget/Assets.xcassets/ProgressBackground.colorset/Contents.json
  ios/ETSMobile Widget/Assets.xcassets/ProgressForeground.colorset/Contents.json
  ios/ETSMobile Widget/Assets.xcassets/WidgetBackground.colorset/Contents.json
  ios/ETSMobile Widget/Constants.swift
  ios/ETSMobile Widget/ETSMobileWidgets.swift
  ios/ETSMobile Widget/Info.plist
  ios/ETSMobile Widget/Model/GradesEntry.swift
  ios/ETSMobile Widget/Model/ProgressEntry.swift
  ios/ETSMobile Widget/Provider/GradesProvider.swift
  ios/ETSMobile Widget/Provider/ProgressProvider.swift
  ios/ETSMobile Widget/View/GradesWidgetEntryView.swift
  ios/ETSMobile Widget/View/ProgressBarView.swift
  ios/ETSMobile Widget/View/ProgressWidgetEntryView.swift
  ios/ETSMobile Widget/View/SingleGradeView.swift
  ios/ETSMobile Widget/Widget/GradesWidget.swift
  ios/ETSMobile Widget/Widget/ProgressWidget.swift
  ios/ETSMobile WidgetExtension.entitlements
  ios/Gemfile.lock
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  ios/fastlane/Matchfile
  ios/fastlane/README.md
  ios/fastlane/report.xml
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/constants/widget_helper.dart
  lib/core/models/widget_models.dart
  lib/core/services/app_widget_service.dart
  lib/core/viewmodels/dashboard_viewmodel.dart
  lib/locator.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
  test/helpers.dart
  test/mock/services/app_widget_service_mock.dart
  test/mock/services/home_widget_mock.dart
  test/services/app_widget_service_test.dart
  test/ui/views/dashboard_view_test.dart
  test/viewmodels/dashboard_viewmodel_test.dart
Labels: enhancement, platform: ios

#464 Fix infinite loading for android users
  lib/core/viewmodels/startup_viewmodel.dart
  pubspec.yaml
  test/viewmodels/startup_viewmodel_test.dart
Labels: bug, platform: android
