Repository ApplETS/Notre-Dame, pull requests merged in 2022-10, with the labels that each got.

#675 Fix Today button in schedule
  lib/core/viewmodels/schedule_viewmodel.dart
  pubspec.yaml
Labels: size: XS, version: Patch

#676 BugFix #480 Prevent course acronyms to move when page is clicked / sc…
  lib/ui/views/grade_details_view.dart
  pubspec.yaml
Labels: size: S, version: Patch

#680 Add gitattributes to prevent githooks from reformatting all files on commit
  .gitattributes
  pubspec.yaml
Labels: size: XS, version: Patch

#682 Dashboard schedule show next day if day already passed
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/managers/settings_manager.dart
  lib/core/viewmodels/dashboard_viewmodel.dart
  lib/ui/views/dashboard_view.dart
  pubspec.lock
  pubspec.yaml
  test/mock/managers/settings_manager_mock.dart
  test/ui/views/dashboard_view_test.dart
  test/ui/views/goldenFiles/gradesDetailsView_1.png
  test/ui/views/goldenFiles/gradesDetailsView_2.png
  test/ui/views/goldenFiles/gradesDetailsView_evaluation_not_completed.png
  test/viewmodels/dashboard_viewmodel_test.dart
Labels: hacktoberfest-accepted, size: M, version: Minor

#677 Add PaperCut feature
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/constants/quick_links.dart
  pubspec.yaml
  test/ui/views/goldenFiles/quicksLinksView_1.png
Labels: hacktoberfest-accepted, size: XS, version: Patch

#694 693: fix golden testing
  .github/pull_request_template.md
  .github/workflows/main-workflow.yaml
  pubspec.yaml
  test/ui/views/about_view_test.dart
  test/ui/views/choose_language_view_test.dart
  test/ui/views/dashboard_view_test.dart
  test/ui/views/feedback_view_test.dart
  test/ui/views/grades_details_view_test.dart
  test/ui/views/grades_view_test.dart
  test/ui/views/more_view_test.dart
  test/ui/views/not_found_view_test.dart
  test/ui/views/profile_view_test.dart
  test/ui/views/quick_links_view_test.dart
  test/ui/views/schedule_view_test.dart
  test/ui/views/settings_view_test.dart
  test/ui/views/student_view_test.dart
  test/ui/widgets/schedule_settings_test.dart
Labels: hacktoberfest-accepted, size: S, version: Patch
