Repository ApplETS/Notre-Dame, pull requests merged in 2022-09, with the labels that each got.

#492 Feature/outage page
  assets/animations/outage.gif
  ios/Podfile.lock
  ios/Runner/Info.plist
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/constants/router_paths.dart
  lib/core/services/navigation_service.dart
  lib/core/services/remote_config_service.dart
  lib/core/viewmodels/outage_viewmodel.dart
  lib/locator.dart
  lib/main.dart
  lib/ui/router.dart
  lib/ui/views/outage_view.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, platform: ios, platform: android, size: M, version: Minor

#479 Add scrolling title when opening evaluation
  lib/ui/widgets/grade_evaluation_tile.dart
  pubspec.lock
  pubspec.yaml
  test/ui/widgets/grade_evaluation_tile_test.dart
Labels: size: S, version: Patch

#501 fix #500 - change portail URL to bypass MFA warning page
  lib/core/constants/quick_links.dart
  pubspec.yaml
Labels: bug, size: XS, version: Patch
