Repository ApplETS/Notre-Dame, pull requests merged in 2022-08, with the labels that each got.

#505 Fix firebase analytics runtime error
  pubspec.lock
  pubspec.yaml
Labels: size: XS

#502 Création d'un template pour les pull_request
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: size: XS

#478 Add CI job to bump app version with PR label
  .github/workflows/devtools-workflow.yaml
  pubspec.yaml
Labels: CI, size: S, github_actions, Amélioration, version: Patch

#509 Feature/add cybermetrics
  lib/core/viewmodels/dashboard_viewmodel.dart
  lib/core/viewmodels/profile_viewmodel.dart
  lib/core/viewmodels/web_link_card_viewmodel.dart
  lib/ui/views/dashboard_view.dart
  lib/ui/views/grades_view.dart
  lib/ui/views/more_view.dart
  lib/ui/views/profile_view.dart
  lib/ui/views/schedule_view.dart
  lib/ui/widgets/bottom_bar.dart
  pubspec.yaml
  test/ui/views/grades_view_test.dart
  test/ui/views/more_view_test.dart
  test/ui/views/profile_view_test.dart
  test/ui/views/schedule_view_test.dart
  test/ui/views/settings_view_test.dart
  test/ui/views/student_view_test.dart
  test/ui/widgets/base_scaffold_test.dart
  test/ui/widgets/bottom_bar_test.dart
  test/viewmodels/dashboard_viewmodel_test.dart
  test/viewmodels/web_link_card_viewmodel_test.dart
Labels: platform: ios, platform: android, size: M, version: Patch
