Repository ApplETS/Notre-Dame, pull requests merged in 2022-11, with the labels that each got.

#702 Add the material 3 supportability
  .github/workflows/main-workflow.yaml
  lib/ui/utils/app_theme.dart
  lib/ui/views/about_view.dart
  lib/ui/views/grade_details_view.dart
  lib/ui/views/not_found_view.dart
  lib/ui/views/student_view.dart
  pubspec.yaml
  test/ui/views/goldenFiles/chooseLanguageView_1.png
  test/ui/views/goldenFiles/dashboardView_appletsCard_1.png
  test/ui/views/goldenFiles/dashboardView_progressBarCard_1.png
  test/ui/views/goldenFiles/dashboardView_scheduleCard_1.png
  test/ui/views/goldenFiles/feedbackView_1.png
  test/ui/views/goldenFiles/gradesDetailsView_1.png
  test/ui/views/goldenFiles/gradesDetailsView_2.png
  test/ui/views/goldenFiles/gradesDetailsView_evaluation_not_completed.png
  test/ui/views/goldenFiles/gradesView_1.png
  test/ui/views/goldenFiles/gradesView_2.png
  test/ui/views/goldenFiles/moreView_1.png
  test/ui/views/goldenFiles/notFoundView_1.png
  test/ui/views/goldenFiles/profileView_1.png
  test/ui/views/goldenFiles/quicksLinksView_1.png
  test/ui/views/goldenFiles/scheduleView_1.png
  test/ui/views/goldenFiles/scheduleView_2.png
  test/ui/views/goldenFiles/scheduleView_3.png
  test/ui/views/goldenFiles/scheduleView_4.png
  test/ui/views/goldenFiles/scheduleView_5.png
  test/ui/views/goldenFiles/settingsView_1.png
  test/ui/views/goldenFiles/studentView_1.png
  test/ui/widgets/goldenFiles/scheduleSettingsView_1.png
  test/viewmodels/feedback_viewmodel_test.dart
Labels: hacktoberfest-accepted, size: S, version: Minor

#706 [TEST-CD] Update release-workflow.yaml
  .github/workflows/release-workflow.yaml
  pubspec.yaml
Labels: size: XS, version: Patch

#709 Feature/bump pubspec versions
  .github/workflows/main-workflow.yaml
  lib/core/utils/utils.dart
  lib/ui/widgets/grade_circular_progress.dart
  pubspec.lock
  pubspec.yaml
Labels: size: S, version: Patch

#721 Feature/bump pubspec version
  .github/workflows/devtools-workflow.yaml
  pubspec.lock
  pubspec.yaml
  test/viewmodels/grades_viewmodel_test.dart
Labels: size: S, version: Patch

#732 Add Easter Egg in About Page
  assets/images/capra_long.png
  lib/ui/views/about_view.dart
  pubspec.lock
  pubspec.yaml
Labels: size: S, version: Minor

#673 BugFix #663 Prevent the submit button from sending github issues mult…
  lib/core/viewmodels/feedback_viewmodel.dart
  lib/ui/views/feedback_view.dart
  pubspec.yaml
  test/viewmodels/feedback_viewmodel_test.dart
Labels: hacktoberfest-accepted, size: S, version: Patch
