Repository ApplETS/Notre-Dame, pull requests merged in 2022-07, with the labels that each got.

#446 Add navigation by map title
  lib/ui/views/dashboard_view.dart
  pubspec.lock
  pubspec.yaml
Labels: size: XS

#447 Fix the semester progression bar.
  lib/core/viewmodels/dashboard_viewmodel.dart
  pubspec.yaml
  test/ui/views/goldenFiles/dashboardView_progressBarCard_1.png
  test/viewmodels/dashboard_viewmodel_test.dart
Labels: size: S

#477 Feature/need help button login page
  .github/workflows/main-workflow.yaml
  .github/workflows/release-workflow.yaml
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/constants/app_info.dart
  lib/core/services/launch_url_service.dart
  lib/core/viewmodels/login_viewmodel.dart
  lib/locator.dart
  lib/ui/views/feedback_view.dart
  lib/ui/views/login_view.dart
  pubspec.yaml
  test/helpers.dart
  test/mock/services/launch_url_service_mock.dart
  test/ui/views/goldenFiles/aboutView_1.png
  test/ui/views/goldenFiles/feedbackView_1.png
  test/ui/views/login_view_test.dart
  test/viewmodels/login_viewmodel_test.dart
Labels: size: M

#448 Fix the scaling of the webview for emergency
  lib/core/viewmodels/emergency_viewmodel.dart
  pubspec.yaml
Labels: size: XS
