Repository ApplETS/Notre-Dame, pull requests merged in 2023-11, with the labels that each got.

#879 Add instagram to our card in the dashboard page
  lib/core/constants/urls.dart
  lib/ui/views/dashboard_view.dart
  pubspec.yaml
  test/ui/views/dashboard_view_test.dart
  test/ui/views/goldenFiles/dashboardView_appletsCard_1.png
Labels: hacktoberfest-accepted, size: XS, version: Minor

#886 Copier le code permanent et code universel au tap
  android/gradle/wrapper/gradle-wrapper.properties
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/ui/views/profile_view.dart
  pubspec.yaml
  test/ui/views/profile_view_test.dart
Labels: size: M, version: Minor

#842 Feature/month view calendar
  lib/core/constants/preferences_flags.dart
  lib/core/viewmodels/grades_details_viewmodel.dart
  lib/core/viewmodels/schedule_settings_viewmodel.dart
  lib/core/viewmodels/schedule_viewmodel.dart
  lib/ui/views/schedule_view.dart
  lib/ui/widgets/schedule_settings.dart
  pubspec.yaml
  test/viewmodels/schedule_settings_viewmodel_test.dart
Labels: hacktoberfest-accepted, size: M, version: Minor

#889 Change broadcast card launch url logic to webview
  lib/core/viewmodels/dashboard_viewmodel.dart
  lib/ui/views/dashboard_view.dart
  pubspec.yaml
Labels: size: XS, version: Patch

#893 Fix quicklinks landscape mode
  lib/core/constants/quick_links.dart
  lib/ui/views/quick_links_view.dart
  lib/ui/widgets/web_link_card.dart
  pubspec.yaml
  test/ui/views/goldenFiles/quicksLinksView_1.png
Labels: size: S, version: Minor

#894 Prepare the CI to easily merge dependabot PRs
  .github/dependabot.yml
  .github/workflows/dev-workflow.yaml
  .github/workflows/devtools-workflow.yaml
  .github/workflows/master-workflow.yaml
Labels: size: M
