Repository ApplETS/Notre-Dame, pull requests merged in 2023-09, with the labels that each got.

#834 Bump pubspec versions
  .github/workflows/master-workflow.yaml
  pubspec.lock
  pubspec.yaml
Labels: size: S, version: Patch

#833 Update profil page
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/constants/programs_credits.dart
  lib/core/managers/course_repository.dart
  lib/core/viewmodels/profile_viewmodel.dart
  lib/ui/views/profile_view.dart
  lib/ui/widgets/student_program.dart
  pubspec.yaml
  test/ui/views/goldenFiles/profileView_1.png
  test/ui/views/profile_view_test.dart
  test/ui/widgets/student_program_test.dart
  test/viewmodels/profile_viewmodel_test.dart
Labels: platform: ios, platform: android, feature: Profile, size: L, version: Minor

#763 Feature/forgot password link
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/constants/urls.dart
  lib/core/managers/settings_manager.dart
  lib/core/services/launch_url_service.dart
  lib/core/viewmodels/web_link_card_viewmodel.dart
  lib/ui/views/login_view.dart
  lib/ui/views/quick_links_view.dart
  lib/ui/widgets/web_link_card.dart
  pubspec.yaml
  test/ui/views/quick_links_view_test.dart
  test/ui/widgets/web_link_card_test.dart
  test/viewmodels/web_link_card_viewmodel_test.dart
Labels: enhancement, size: M, version: Minor

#841 Hotfix/update target sdk
  android/app/build.gradle
  ios/Gemfile.lock
  pubspec.yaml
Labels: size: XS, version: Patch

#827 Feature/News Card Component
  lib/core/managers/news_repository.dart
  lib/core/models/news.dart
  lib/core/models/tags.dart
  lib/core/utils/utils.dart
  lib/core/viewmodels/news_viewmodel.dart
  lib/locator.dart
  lib/ui/views/dashboard_view.dart
  pubspec.lock
  pubspec.yaml
  test/managers/news_repository_test.dart
  test/models/news_test.dart
  test/viewmodels/news_viewmodel_test.dart
Labels: enhancement, size: L, version: Minor, hello

#846 Fix program selection for profile page
  lib/core/constants/programs_credits.dart
  lib/core/viewmodels/profile_viewmodel.dart
Labels: version: Patch

#852 Fix program selection for profile page (#846)
  lib/core/constants/programs_credits.dart
  lib/core/viewmodels/profile_viewmodel.dart
  lib/l10n/intl_en.arb
  pubspec.yaml
Labels: size: XS, version: Patch

#849 Feature/reordable links
  ios/Podfile.lock
  lib/core/constants/quick_links.dart
  lib/core/managers/quick_link_repository.dart
  lib/core/models/quick_link.dart
  lib/core/models/quick_link_data.dart
  lib/core/viewmodels/quick_links_viewmodel.dart
  lib/locator.dart
  lib/ui/views/quick_links_view.dart
  pubspec.lock
  pubspec.yaml
  test/helpers.dart
  test/managers/quick_link_repository_test.dart
  test/mock/managers/quick_links_repository_mock.dart
  test/ui/views/goldenFiles/quicksLinksView_1.png
  test/ui/views/quick_links_view_test.dart
  test/ui/widgets/link_web_view_test.dart
  test/ui/widgets/web_link_card_test.dart
  test/viewmodels/quick_links_viewmodel_test.dart
  test/viewmodels/web_link_card_viewmodel_test.dart
Labels: size: L, version: Minor

#850 Add FAQ page
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/constants/discovery_ids.dart
  lib/core/constants/faq.dart
  lib/core/constants/router_paths.dart
  lib/core/models/faq_actions.dart
  lib/core/models/faq_questions.dart
  lib/core/viewmodels/faq_viewmodel.dart
  lib/core/viewmodels/login_viewmodel.dart
  lib/ui/router.dart
  lib/ui/utils/discovery_components.dart
  lib/ui/views/faq_view.dart
  lib/ui/views/login_view.dart
  lib/ui/views/more_view.dart
  pubspec.lock
  pubspec.yaml
  test/ui/views/faq_view_test.dart
  test/ui/views/goldenFiles/FaqView_1.png
  test/ui/views/goldenFiles/moreView_1.png
  test/ui/views/login_view_test.dart
  test/ui/views/more_view_test.dart
  test/viewmodels/faq_viewmodel_test.dart
  test/viewmodels/login_viewmodel_test.dart
Labels: platform: ios, platform: android, size: L, version: Minor

#853 Add a customizable card in the dashboard
  lib/core/constants/preferences_flags.dart
  lib/core/managers/settings_manager.dart
  lib/core/services/remote_config_service.dart
  lib/core/viewmodels/dashboard_viewmodel.dart
  lib/ui/views/dashboard_view.dart
  pubspec.yaml
  test/managers/settings_manager_test.dart
  test/mock/services/remote_config_service_mock.dart
  test/ui/views/dashboard_view_test.dart
  test/viewmodels/dashboard_viewmodel_test.dart
Labels: size: L, version: Minor
