Repository ApplETS/Notre-Dame, pull requests merged in 2023-01, with the labels that each got.

#746 Bump pubspec version
  .github/workflows/main-workflow.yaml
  pubspec.lock
  pubspec.yaml
Labels: size: S, version: Patch

#748 Add the possibility to swipe to go to the next day or weak
  lib/core/managers/course_repository.dart
  lib/core/services/internal_info_service.dart
  lib/core/services/remote_config_service.dart
  lib/core/viewmodels/dashboard_viewmodel.dart
  lib/core/viewmodels/grades_details_viewmodel.dart
  lib/core/viewmodels/grades_viewmodel.dart
  lib/core/viewmodels/more_viewmodel.dart
  lib/core/viewmodels/outage_viewmodel.dart
  lib/core/viewmodels/schedule_viewmodel.dart
  lib/main.dart
  lib/ui/utils/discovery_components.dart
  lib/ui/views/feedback_view.dart
  lib/ui/views/schedule_view.dart
  pubspec.yaml
  test/ui/views/not_found_view_test.dart
  test/ui/widgets/grade_button_test.dart
  test/viewmodels/not_found_viewmodel_test.dart
  test/viewmodels/web_link_card_viewmodel_test.dart
Labels: size: M, version: Minor

#707 Separate dev and master pipelines
  .github/workflows/comment-artifacts-workflow.yaml
  .github/workflows/dev-workflow.yaml
  .github/workflows/devtools-workflow.yaml
  .github/workflows/master-workflow.yaml
  pubspec.yaml
Labels: size: M, version: Patch

#758 Fix build status badge in readme
  README.fr.md
  README.md
Labels: version: Patch

#703 Feature/feedback list
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/constants/preferences_flags.dart
  lib/core/models/feedback_issue.dart
  lib/core/services/github_api.dart
  lib/core/viewmodels/feedback_viewmodel.dart
  lib/ui/views/feedback_view.dart
  pubspec.yaml
  test/mock/services/github_api_mock.dart
  test/models/feedback_issue_test.dart
  test/ui/views/feedback_view_test.dart
  test/ui/views/goldenFiles/feedbackView_1.png
  test/viewmodels/feedback_viewmodel_test.dart
Labels: hacktoberfest-accepted, size: M, version: Minor

#760 Remove testing racing condition in dev-workflow
  .github/workflows/dev-workflow.yaml
  pubspec.yaml
Labels: size: XS, version: Patch

#759 Add credits to course details page
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/ui/views/grade_details_view.dart
  pubspec.yaml
  test/ui/views/goldenFiles/gradesDetailsView_1.png
  test/ui/views/goldenFiles/gradesDetailsView_2.png
  test/ui/views/goldenFiles/gradesDetailsView_evaluation_not_completed.png
  test/ui/views/grades_details_view_test.dart
Labels: size: XS, version: Patch

#708 Feature/improve bug report feature
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/constants/custom_feedback_localization.dart
  lib/core/constants/feedback_type.dart
  lib/core/models/feedback.dart
  lib/core/services/github_api.dart
  lib/core/viewmodels/feedback_viewmodel.dart
  lib/main.dart
  lib/ui/utils/app_theme.dart
  lib/ui/views/feedback_view.dart
  lib/ui/widgets/custom_feedback.dart
  pubspec.yaml
  test/ui/views/feedback_view_test.dart
  test/ui/views/goldenFiles/feedbackView_1.png
  test/ui/views/goldenFiles/moreView_1.png
  test/viewmodels/feedback_viewmodel_test.dart
Labels: platform: ios, platform: android, size: M, version: Minor

#762 Fix play store badge
  README.md
Labels: version: Patch
