Repository ApplETS/Notre-Dame, pull requests merged in 2023-03, with the labels that each got.

#788 Fix today button in calendar view and add settings in schedule settings.
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/constants/preferences_flags.dart
  lib/core/managers/settings_manager.dart
  lib/core/viewmodels/schedule_settings_viewmodel.dart
  lib/core/viewmodels/schedule_viewmodel.dart
  lib/ui/views/schedule_view.dart
  lib/ui/widgets/schedule_settings.dart
  pubspec.yaml
  test/managers/settings_manager_test.dart
  test/ui/widgets/schedule_settings_test.dart
Labels: size: M, version: Patch

#799 Fix bug/enhancement report
  lib/core/services/github_api.dart
  lib/core/viewmodels/feedback_viewmodel.dart
  lib/ui/views/feedback_view.dart
  pubspec.yaml
  test/viewmodels/feedback_viewmodel_test.dart
Labels: bug, size: S, version: Patch

#800 Fix the bug from the outage page
  lib/core/constants/router_paths.dart
  lib/core/viewmodels/outage_viewmodel.dart
  lib/ui/router.dart
  pubspec.yaml
Labels: feature: bug report, size: XS, version: Patch
