Repository ApplETS/Notre-Dame, pull requests merged in 2024-04, with the labels that each got.

#961 Get organizer events for Author view
  lib/core/managers/author_repository.dart
  lib/core/managers/news_repository.dart
  lib/core/models/author.dart
  lib/core/models/social_link.dart
  lib/core/viewmodels/author_viewmodel.dart
  lib/core/viewmodels/report_news_viewmodel.dart
  lib/ui/views/author_view.dart
  lib/ui/views/news_details_view.dart
  lib/ui/views/news_view.dart
  lib/ui/widgets/news_card.dart
  lib/ui/widgets/report_news.dart
  lib/ui/widgets/social_links_card.dart
  pubspec.lock
  test/managers/author_repository_test.dart
  test/mock/managers/author_repository_mock.dart
  test/mock/managers/news_repository_mock.dart
  test/ui/views/author_view_test.dart
  test/ui/views/ets_view_test.dart
  test/ui/views/goldenFiles/authorView_1.png
  test/ui/views/goldenFiles/authorView_2.png
  test/ui/views/news_details_view_test.dart
  test/ui/views/news_view_test.dart
  test/ui/widgets/news_card_test.dart
  test/viewmodels/author_viewmodel_test.dart
  test/viewmodels/news_details_viewmodel_test.dart
  test/viewmodels/news_viewmodel_test.dart
Labels: size: L, version: Minor, hello

#963 Report news
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/constants/report_news.dart
  lib/core/models/report_news.dart
  lib/core/viewmodels/report_news_viewmodel.dart
  lib/ui/views/news_details_view.dart
  lib/ui/widgets/report_news.dart
  pubspec.lock
  test/models/report_news_test.dart
Labels: size: M, version: Minor, hello

#964 Hello/feature/search news
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/managers/news_repository.dart
  lib/core/viewmodels/news_viewmodel.dart
  lib/ui/views/news_view.dart
Labels: size: M, version: Minor, hello

#960 Ci/add unversioned label
  .github/workflows/devtools-workflow.yaml
Labels: CI, size: XS, version - Unversioned

#965 Feature/update dependencies
  .githooks/pre-commit
  lib/core/extensions/webview_controller_extension.dart
  lib/core/services/networking_service.dart
  lib/ui/views/emergency_view.dart
  lib/ui/widgets/base_scaffold.dart
  lib/ui/widgets/link_web_view.dart
  pubspec.lock
  pubspec.yaml
  test/mock/services/networking_service_mock.dart
  test/ui/views/emergency_view_test.dart
  test/ui/widgets/link_web_view_test.dart
Labels: size: M, version: Minor

#966 Put bump_version into its own workflow
  .github/workflows/devtools-workflow.yaml
  .github/workflows/versionning-workflow.yaml
Labels: version - Unversioned

#907 Fix repeated colors in schedule cards
  lib/core/viewmodels/schedule_viewmodel.dart
  lib/ui/utils/app_theme.dart
  lib/ui/views/schedule_view.dart
Labels: size: S, version: Patch

#926 Fix duplicated courses in dashboard
  lib/core/viewmodels/dashboard_viewmodel.dart
  pubspec.yaml
Labels: bug, platform: ios, platform: android, feature: Dashboard, size: XS, version: Minor

#967 Fixed missing cache keys when loading profile page on first install
  lib/core/managers/course_repository.dart
  lib/core/managers/user_repository.dart
  pubspec.yaml
Labels: bug, feature: Profile, size: XS, version: Patch

#969 Fix dark theme text color
  lib/ui/utils/app_theme.dart
  pubspec.yaml
Labels: size: XS, version: Minor

#959 Update Podfile.lock
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  pubspec.yaml
Labels: size: M, version: Patch
