Repository ApplETS/Notre-Dame, pull requests merged in 2024-10, with the labels that each got.

#1058 Update to latest Flutter version
  android/gradle/wrapper/gradle-wrapper.properties
  assets/animations/dot_jumping.riv
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/AppDelegate.swift
  lib/features/app/error/not_found/not_found_view.dart
  lib/features/app/error/not_found/not_found_viewmodel.dart
  lib/features/app/presentation/rive_animation_service.dart
  lib/features/app/widgets/bottom_bar.dart
  lib/features/app/widgets/navigation_rail.dart
  lib/features/dashboard/dashboard_view.dart
  lib/features/dashboard/dashboard_viewmodel.dart
  lib/features/more/more_view.dart
  lib/features/more/more_viewmodel.dart
  lib/features/schedule/schedule_view.dart
  lib/features/schedule/schedule_viewmodel.dart
  lib/features/student/grades/grade_details/grades_details_viewmodel.dart
  lib/features/student/grades/grades_viewmodel.dart
  lib/features/student/grades/widgets/grade_button.dart
  lib/features/student/grades/widgets/grade_evaluation_tile.dart
  lib/features/student/student_view.dart
  lib/features/welcome/discovery/discovery_components.dart
  lib/main.dart
  lib/utils/locator.dart
  pubspec.lock
  pubspec.yaml
  test/common/helpers.dart
  test/features/app/error/not_found/not_found_view_test.dart
  test/features/app/error/not_found/not_found_viewmodel_test.dart
  test/features/app/presentation/mocks/rive_animation_service_mock.dart
  test/features/app/widgets/base_scaffold_test.dart
  test/features/app/widgets/bottom_bar_test.dart
  test/features/dashboard/dashboard_view_test.dart
  test/features/ets/ets_view_test.dart
  test/features/ets/quick-link/quick_links_view_test.dart
  test/features/more/more_view_test.dart
  test/features/more/settings/settings_view_test.dart
  test/features/schedule/schedule_view_test.dart
  test/features/student/grades/grade_details/grades_details_view_test.dart
  test/features/student/grades/grades_view_test.dart
  test/features/student/grades/widgets/grade_evaluation_tile_test.dart
  test/features/student/student_view_test.dart
Labels: size: L, version: Minor

#1062 Update ci flutter version
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/profile/AndroidManifest.xml
  android/build.gradle
  ios/Podfile.lock
  lib/features/app/error/outage/outage_view.dart
  lib/features/app/error/outage/outage_viewmodel.dart
  lib/features/app/error/outage/widgets/outage_text_section.dart
  lib/features/app/widgets/base_scaffold.dart
  lib/features/dashboard/dashboard_view.dart
  lib/features/dashboard/widgets/course_activity_tile.dart
  lib/features/ets/events/author/author_view.dart
  lib/features/ets/events/news/news-details/news_details_view.dart
  lib/features/ets/events/report-news/report_news_widget.dart
  lib/features/ets/quick-link/widgets/security-info/emergency_view.dart
  lib/features/ets/quick-link/widgets/security-info/security_view.dart
  lib/features/more/faq/faq_view.dart
  lib/features/more/feedback/feedback_view.dart
  lib/features/more/more_viewmodel.dart
  lib/features/schedule/schedule_viewmodel.dart
  lib/features/student/grades/grade_details/grades_details_viewmodel.dart
  lib/features/student/grades/grades_viewmodel.dart
  lib/features/welcome/login/login_view.dart
  pubspec.lock
  pubspec.yaml
  test/features/dashboard/dashboard_view_test.dart
  test/features/dashboard/dashboard_viewmodel_test.dart
  test/features/ets/quick-link/widgets/security-info/emergency_view_test.dart
Labels: size: M

#1056 Bugfix/1026 Android back gesture should follow navigation history
  lib/features/app/navigation/navigation_history_observer.dart
  lib/features/app/navigation/navigation_service.dart
  lib/features/app/widgets/bottom_bar.dart
  lib/features/app/widgets/navigation_rail.dart
  lib/main.dart
  pubspec.yaml
  test/features/app/widgets/bottom_bar_test.dart
Labels: bug, size: M, Amélioration, version: Patch
