Repository ApplETS/Notre-Dame, pull requests merged in 2024-07, with the labels that each got.

#998 Change marquee to singlescrollview
  lib/features/student/grades/widgets/grade_evaluation_tile.dart
  pubspec.lock
  pubspec.yaml
Labels: size: M, version: Patch

#1011 Outlined icons
  ios/Podfile.lock
  lib/features/app/widgets/base_scaffold.dart
  lib/features/app/widgets/bottom_bar.dart
  lib/features/app/widgets/navigation_rail.dart
  lib/features/more/feedback/feedback_view.dart
  lib/features/more/more_view.dart
  lib/features/schedule/schedule_view.dart
  pubspec.yaml
  test/ui/views/goldenFiles/newsDetailsView_1.png
  test/ui/views/schedule_view_test.dart
  test/ui/widgets/bottom_bar_test.dart
Labels: size: S, version: Minor

#1004 Need help page improvements
  lib/features/more/faq/faq_view.dart
  test/ui/views/faq_view_test.dart
  test/ui/views/goldenFiles/FaqView_1.png
Labels: size: M, version: Minor

#1012 Fix export calendar on iOS
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/features/schedule/widgets/calendar_selector.dart
  lib/utils/calendar_utils.dart
  pubspec.yaml
Labels: feature: Schedule, size: S, version: Minor

#1003 Pfe master f3.1
  lib/features/dashboard/widgets-dashboard/about_us_card.dart
  lib/features/dashboard/widgets-dashboard/grades_card.dart
  lib/features/dashboard/widgets-dashboard/message_broadcast_card.dart
  lib/features/dashboard/widgets-dashboard/progress_bar_card.dart
  lib/features/dashboard/widgets-dashboard/schedule_card.dart
  lib/features/ets/events/author/author_view.dart
  lib/features/ets/events/author/author_viewmodel.dart
  lib/features/ets/events/author/widget/author_info_widget.dart
  lib/features/ets/events/author/widget/avatar_widget.dart
  lib/features/ets/events/author/widget/back_button_widget.dart
  lib/features/ets/events/author/widget/no_more_news_card_widget.dart
  lib/features/ets/quick-link/widgets/security-info/emergency_view.dart
  lib/features/ets/quick-link/widgets/security-info/widget/emergency_floating_button.dart
  lib/features/more/about/about_view.dart
  lib/features/more/about/widget/easter_egg_icon.dart
  lib/features/more/about/widget/social_icons_row.dart
  lib/features/more/contributors/contributors_view.dart
  lib/features/more/contributors/widgets/contributor_title_widget.dart
  lib/features/more/faq/faq_view.dart
  lib/features/more/faq/widget/action_card.dart
  lib/features/more/faq/widget/faq_subtitle.dart
  lib/features/more/faq/widget/faq_title.dart
  lib/features/more/faq/widget/question_card.dart
  lib/features/more/feedback/feedback_view.dart
  lib/features/more/feedback/widgets-feedback/card_info.dart
  lib/features/more/feedback/widgets-feedback/list_tag.dart
  lib/features/more/more_view.dart
  lib/features/more/more_viewmodel.dart
  lib/features/more/settings/choose_language_view.dart
  lib/features/more/settings/widget/language_card_widget.dart
  lib/features/more/settings/widget/language_list_widget.dart
  lib/features/more/widget/about_applets_tile.dart
  lib/features/more/widget/contributors_list_tile.dart
  lib/features/more/widget/in_app_review_tile.dart
  lib/features/more/widget/open_source_licenses_list_tile.dart
  lib/features/more/widget/report_bug_tile.dart
  lib/features/student/grades/grade_details/grade_details_view.dart
  lib/features/student/grades/grade_details/widget/class_info.dart
  lib/features/student/grades/grade_details/widget/course_grade_summary.dart
  lib/features/student/grades/grade_details/widget/grade_evaluations.dart
  lib/features/student/grades/grade_details/widget/grade_summary.dart
  lib/features/student/grades/grades_view.dart
  lib/features/student/grades/widget-grade-view/empty_grades_message.dart
  lib/features/student/grades/widget-grade-view/grade_list.dart
  lib/features/student/grades/widget-grade-view/grade_session_courses.dart
  lib/features/welcome/login/login_view.dart
  lib/features/welcome/login/widget/app_ets_logo.dart
  lib/features/welcome/login/widget/forgot_password_link.dart
  lib/features/welcome/login/widget/login_button.dart
  lib/features/welcome/login/widget/login_widget.dart
  lib/features/welcome/login/widget/need_help_link.dart
  lib/features/welcome/login/widget/universal_code_field.dart
  test/ui/views/goldenFiles/authorView_1.png
  test/ui/views/goldenFiles/authorView_2.png
  test/ui/views/goldenFiles/gradesDetailsView_1.png
  test/ui/views/goldenFiles/gradesDetailsView_2.png
  test/ui/views/goldenFiles/gradesDetailsView_evaluation_not_completed.png
  test/ui/views/goldenFiles/newsDetailsView_1.png
  test/viewmodels/more_viewmodel_test.dart
Labels: size: XL, Amélioration, version - Unversioned

#1014 Permettre aux utilisateurs sur iOS de swipe pour retourner à la page précédente
  lib/features/app/navigation/router.dart
Labels: size: S, Amélioration, version: Minor

#1015 Add skeletons
  l10n/intl_fr.arb
  lib/features/app/widgets/base_scaffold.dart
  lib/features/dashboard/dashboard_view.dart
  lib/features/dashboard/dashboard_viewmodel.dart
  lib/features/dashboard/widgets/course_activity_tile.dart
  lib/features/more/contributors/contributors_view.dart
  lib/features/student/grades/widgets/grade_button.dart
  pubspec.yaml
Labels: size: M, version: Minor

#1016 Small spacing corrections
  lib/features/ets/quick-link/quick_links_view.dart
  lib/features/ets/quick-link/widgets/security-info/security_view.dart
  lib/features/student/grades/grade_details/grade_details_view.dart
  lib/features/student/student_view.dart
  pubspec.yaml
  test/ui/views/goldenFiles/gradesDetailsView_1.png
  test/ui/views/goldenFiles/gradesDetailsView_evaluation_not_completed.png
  test/ui/views/goldenFiles/newsDetailsView_1.png
  test/ui/views/goldenFiles/quicksLinksView_1.png
Labels: size: M, version: Minor

#1018 Add animation
  lib/features/app/navigation/router.dart
  pubspec.yaml
  test/ui/views/goldenFiles/newsDetailsView_1.png
Labels: size: XS, version: Minor

#1022 update capra logo
  assets/images/capra.png
  assets/images/capra_long.png
  lib/features/more/about/about_view.dart
Labels: size: XS

#1021 Fix overflow grade details
  lib/features/student/grades/grade_details/grade_details_view.dart
  lib/features/student/grades/widgets/grade_not_available.dart
  pubspec.yaml
  test/ui/views/goldenFiles/gradesDetailsView_1.png
  test/ui/views/goldenFiles/gradesDetailsView_evaluation_not_completed.png
Labels: size: M, version: Minor

#1020 Better dark theme support, more efficient use of space for schedule view
  lib/features/schedule/schedule_view.dart
Labels: size: S, version: Minor

#1023 Hotfix/#882 fix dashboard reorganisation
  lib/constants/preferences_flags.dart
  lib/features/dashboard/dashboard_view.dart
  lib/features/dashboard/dashboard_viewmodel.dart
  lib/features/more/settings/settings_manager.dart
  pubspec.lock
  pubspec.yaml
  test/managers/settings_manager_test.dart
  test/ui/views/dashboard_view_test.dart
  test/ui/views/goldenFiles/dashboardView_appletsCard_1.png
  test/ui/views/goldenFiles/dashboardView_progressBarCard_1.png
  test/ui/views/goldenFiles/dashboardView_scheduleCard_1.png
  test/ui/views/schedule_default_view_test.dart
  test/viewmodels/dashboard_viewmodel_test.dart
Labels: size: M, version: Patch

#1029 Increase contrast in grades detail page
  lib/features/student/grades/grade_details/grade_details_view.dart
  lib/features/student/grades/widgets/grade_evaluation_tile.dart
  pubspec.yaml
  test/ui/views/goldenFiles/gradesDetailsView_1.png
  test/ui/views/goldenFiles/gradesDetailsView_2.png
  test/ui/views/goldenFiles/gradesDetailsView_evaluation_not_completed.png
  test/ui/views/grades_details_view_test.dart
Labels: size: M, version: Patch

#1031 Bufix return to current day
  lib/features/schedule/schedule_viewmodel.dart
  pubspec.yaml
  test/ui/views/goldenFiles/newsDetailsView_1.png
  test/viewmodels/schedule_viewmodel_test.dart
Labels: size: XS, version: Patch

#1030 Default schedule improvements
  lib/features/app/navigation/router.dart
  lib/features/schedule/schedule_default/schedule_default.dart
  lib/features/schedule/schedule_default/schedule_default_view.dart
  lib/features/schedule/schedule_default/schedule_default_viewmodel.dart
  lib/features/schedule/widgets/schedule_calendar_tile.dart
  lib/utils/loading.dart
  pubspec.yaml
  test/ui/widgets/schedule_default_test.dart
Labels: size: M, version: Minor
