Repository ApplETS/Notre-Dame, pull requests merged in 2024-11, with the labels that each got.

#1048 Automatically show weekend days
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/constants/preferences_flags.dart
  lib/features/more/settings/settings_manager.dart
  lib/features/schedule/schedule_default/schedule_default.dart
  lib/features/schedule/schedule_default/schedule_default_view.dart
  lib/features/schedule/schedule_default/schedule_default_viewmodel.dart
  lib/features/schedule/schedule_settings_viewmodel.dart
  lib/features/schedule/schedule_view.dart
  lib/features/schedule/schedule_viewmodel.dart
  lib/features/schedule/widgets/schedule_settings.dart
  lib/utils/calendar_utils.dart
  lib/utils/utils.dart
  test/features/more/settings/settings_manager_test.dart
  test/features/schedule/schedule_defaut/schedule_default_test.dart
  test/features/schedule/schedule_defaut/schedule_default_viewmodel_test.dart
  test/features/schedule/schedule_settings_viewmodel_test.dart
  test/features/schedule/schedule_view_test.dart
  test/features/schedule/schedule_viewmodel_test.dart
  test/features/schedule/widgets/schedule_settings_test.dart
Labels: size: XL, version: Minor

#1083 Feature/refactor login view
  lib/features/welcome/login/login_view.dart
  lib/features/welcome/widgets/forgot_password.dart
  lib/features/welcome/widgets/login_button.dart
  lib/features/welcome/widgets/login_footer.dart
  lib/features/welcome/widgets/login_hero.dart
  lib/features/welcome/widgets/password_text_field.dart
  lib/features/welcome/widgets/universal_code_text_field.dart
  pubspec.yaml
Labels: size: L, feature: auth, version: Minor

#1086 Implement edge to edge on android
  lib/features/app/widgets/base_scaffold.dart
  lib/main.dart
  pubspec.yaml
Labels: enhancement, size: XS, version: Minor

#1092 Empêcher une mise a jour de dépendance de briser le projet
  pubspec.lock
  pubspec.yaml
Labels: size: S, version: Patch

#1091 Remove flutter_custom_tabs
  ios/Podfile.lock
  lib/features/app/error/outage/widgets/outage_social_section.dart
  lib/features/app/integration/launch_url_service.dart
  lib/features/app/navigation/router.dart
  lib/features/app/navigation/router_paths.dart
  lib/features/app/widgets/link_web_view.dart
  lib/features/dashboard/dashboard_view.dart
  lib/features/dashboard/dashboard_viewmodel.dart
  lib/features/ets/events/social/social_links_card.dart
  lib/features/ets/quick-link/widgets/security-info/emergency_view.dart
  lib/features/ets/quick-link/widgets/security-info/security_view.dart
  lib/features/ets/quick-link/widgets/web_link_card.dart
  lib/features/ets/quick-link/widgets/web_link_card_viewmodel.dart
  lib/features/more/about/about_view.dart
  lib/features/more/contributors/contributors_view.dart
  lib/features/more/faq/faq_view.dart
  lib/features/more/faq/faq_viewmodel.dart
  lib/features/more/feedback/feedback_view.dart
  lib/features/more/more_view.dart
  lib/features/more/more_viewmodel.dart
  lib/features/schedule/schedule_view.dart
  lib/features/welcome/widgets/forgot_password.dart
  lib/utils/utils.dart
  pubspec.lock
  pubspec.yaml
  test/features/app/integration/mocks/launch_url_service_mock.dart
  test/features/app/widgets/link_web_view_test.dart
  test/features/dashboard/dashboard_view_test.dart
  test/features/ets/quick-link/widgets/security-info/emergency_view_test.dart
  test/features/ets/quick-link/widgets/security-info/security_view_test.dart
  test/features/ets/quick-link/widgets/web_link_card_viewmodel_test.dart
  test/features/more/about/about_view_test.dart
  test/features/more/faq/faq_viewmodel_test.dart
  test/features/more/feedback/models/feedback_view_test.dart
  test/features/more/more_view_test.dart
Labels: size: L, version: Patch

#1090 Refactor nav bar
  lib/features/app/widgets/base_scaffold.dart
  lib/features/app/widgets/bottom_bar.dart
  lib/features/app/widgets/navigation/base_navigation_bar.dart
  lib/features/app/widgets/navigation/bottom_bar.dart
  lib/features/app/widgets/navigation/navigation_rail.dart
  lib/features/app/widgets/navigation_rail.dart
  test/features/app/widgets/bottom_bar_test.dart
Labels: size: M, version: Patch

#1099 Remove report bug feature
  lib/features/app/analytics/remote_config_service.dart
  lib/features/app/integration/github_api.dart
  lib/features/app/navigation/router.dart
  lib/features/app/navigation/router_paths.dart
  lib/features/more/feedback/feedback_type.dart
  lib/features/more/feedback/feedback_view.dart
  lib/features/more/feedback/feedback_viewmodel.dart
  lib/features/more/feedback/models/custom_feedback_localization.dart
  lib/features/more/feedback/models/feedback.dart
  lib/features/more/feedback/models/feedback_issue.dart
  lib/features/more/feedback/widgets/custom_feedback.dart
  lib/features/more/more_view.dart
  lib/main.dart
  lib/utils/locator.dart
  pubspec.lock
  pubspec.yaml
  test/common/helpers.dart
  test/features/app/integration/mocks/github_api_mock.dart
  test/features/more/feedback/feedback_viewmodel_test.dart
  test/features/more/feedback/models/feedback_issue_test.dart
  test/features/more/feedback/models/feedback_view_test.dart
  test/features/more/more_view_test.dart
Labels: size: XL

#1084 Replace auto size text
  ios/Podfile.lock
  lib/features/dashboard/dashboard_view.dart
  lib/features/schedule/widgets/schedule_calendar_tile.dart
  pubspec.lock
  pubspec.yaml
Labels: size: XS, version: Patch

#1089 Remove percent_indicator lib
  lib/features/student/grades/widgets/grade_circular_indicator.dart
  lib/features/student/grades/widgets/grade_circular_progress.dart
  lib/features/student/profile/profile_view.dart
  lib/features/student/profile/program_completion.dart
  pubspec.lock
  pubspec.yaml
  test/features/student/grades/widgets/grade_circular_progress_test.dart
  test/features/student/profile/profile_view_test.dart
Labels: size: M, version: Patch
