Repository ApplETS/Notre-Dame, pull requests merged in 2024-08, with the labels that each got.

#1032 Refactor/create composite actions
  .github/composite/ci-build/action.yaml
  .github/composite/flutter-setup/action.yaml
  .github/composite/tag-validation/action.yaml
  .github/composite/tests/action.yaml
  .github/pull_request_template.md
  .github/workflows/dev-workflow.yaml
  .github/workflows/master-workflow.yaml
  .github/workflows/release-workflow.yaml
  test/ui/views/about_view_test.dart
  test/ui/views/author_view_test.dart
  test/ui/views/choose_language_view_test.dart
  test/ui/views/dashboard_view_test.dart
  test/ui/views/ets_view_test.dart
  test/ui/views/faq_view_test.dart
  test/ui/views/feedback_view_test.dart
  test/ui/views/goldenFiles/FaqView_1.png
  test/ui/views/goldenFiles/aboutView_1.png
  test/ui/views/goldenFiles/authorView_1.png
  test/ui/views/goldenFiles/authorView_2.png
  test/ui/views/goldenFiles/chooseLanguageView_1.png
  test/ui/views/goldenFiles/dashboardView_appletsCard_1.png
  test/ui/views/goldenFiles/dashboardView_progressBarCard_1.png
  test/ui/views/goldenFiles/dashboardView_scheduleCard_1.png
  test/ui/views/goldenFiles/etsView_1.png
  test/ui/views/goldenFiles/feedbackView_1.png
  test/ui/views/goldenFiles/gradesDetailsView_1.png
  test/ui/views/goldenFiles/gradesDetailsView_2.png
  test/ui/views/goldenFiles/gradesDetailsView_evaluation_not_completed.png
  test/ui/views/goldenFiles/gradesView_1.png
  test/ui/views/goldenFiles/gradesView_2.png
  test/ui/views/goldenFiles/moreView_1.png
  test/ui/views/goldenFiles/newsDetailsView_1.png
  test/ui/views/goldenFiles/newsView_1.png
  test/ui/views/goldenFiles/newsView_2.png
  test/ui/views/goldenFiles/notFoundView_1.png
  test/ui/views/goldenFiles/profileView_1.png
  test/ui/views/goldenFiles/quicksLinksView_1.png
  test/ui/views/goldenFiles/scheduleDefaultView_1.png
  test/ui/views/goldenFiles/scheduleDefaultView_2.png
  test/ui/views/goldenFiles/scheduleView_1.png
  test/ui/views/goldenFiles/scheduleView_2.png
  test/ui/views/goldenFiles/scheduleView_3.png
  test/ui/views/goldenFiles/scheduleView_4.png
  test/ui/views/goldenFiles/scheduleView_5.png
  test/ui/views/goldenFiles/settingsView_1.png
  test/ui/views/goldenFiles/studentView_1.png
  test/ui/views/grades_details_view_test.dart
  test/ui/views/grades_view_test.dart
  test/ui/views/more_view_test.dart
  test/ui/views/news_details_view_test.dart
  test/ui/views/news_view_test.dart
  test/ui/views/not_found_view_test.dart
  test/ui/views/profile_view_test.dart
  test/ui/views/quick_links_view_test.dart
  test/ui/views/schedule_default_view_test.dart
  test/ui/views/schedule_view_test.dart
  test/ui/views/settings_view_test.dart
  test/ui/views/student_view_test.dart
  test/ui/widgets/goldenFiles/scheduleSettingsView_1.png
  test/ui/widgets/schedule_settings_test.dart
Labels: size: XL

#1038 Use markdow to display emergency instructions instead of webview
  assets/html/armed_person_detail_en.html
  assets/html/armed_person_detail_fr.html
  assets/html/bomb_threat_detail_en.html
  assets/html/bomb_threat_detail_fr.html
  assets/html/broken_elevator_detail_en.html
  assets/html/broken_elevator_detail_fr.html
  assets/html/earthquake_detail_en.html
  assets/html/earthquake_detail_fr.html
  assets/html/electrical_outage_detail_en.html
  assets/html/electrical_outage_detail_fr.html
  assets/html/evacuation_detail_en.html
  assets/html/evacuation_detail_fr.html
  assets/html/fire_detail_en.html
  assets/html/fire_detail_fr.html
  assets/html/gas_leak_detail_en.html
  assets/html/gas_leak_detail_fr.html
  assets/html/medical_emergency_detail_en.html
  assets/html/medical_emergency_detail_fr.html
  assets/html/suspicious_packages_detail_en.html
  assets/html/suspicious_packages_detail_fr.html
  assets/markdown/armed_person_en.md
  assets/markdown/armed_person_fr.md
  assets/markdown/bomb_threat_en.md
  assets/markdown/bomb_threat_fr.md
  assets/markdown/broken_elevator_en.md
  assets/markdown/broken_elevator_fr.md
  assets/markdown/earthquake_en.md
  assets/markdown/earthquake_fr.md
  assets/markdown/electrical_outage_en.md
  assets/markdown/electrical_outage_fr.md
  assets/markdown/evacuation_en.md
  assets/markdown/evacuation_fr.md
  assets/markdown/fire_en.md
  assets/markdown/fire_fr.md
  assets/markdown/gas_leak_en.md
  assets/markdown/gas_leak_fr.md
  assets/markdown/medical_emergency_en.md
  assets/markdown/medical_emergency_fr.md
  assets/markdown/suspicious_packages_en.md
  assets/markdown/suspicious_packages_fr.md
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/features/app/presentation/webview_controller_extension.dart
  lib/features/ets/quick-link/widgets/security-info/emergency_view.dart
  lib/features/ets/quick-link/widgets/security-info/models/emergency_procedures.dart
  pubspec.yaml
  test/ui/views/emergency_view_test.dart
Labels: size: XL, version: Minor

#1035 Fix paddings, safe areas and drag animations
  lib/features/ets/quick-link/quick_links_view.dart
  lib/features/ets/quick-link/widgets/security-info/security_view.dart
  lib/features/more/settings/settings_view.dart
  lib/features/schedule/schedule_default/schedule_default.dart
  lib/features/schedule/schedule_view.dart
  lib/features/student/grades/grades_view.dart
  test/ui/views/security_view_test.dart
Labels: size: M, version: Patch
