Repository ApplETS/Notre-Dame, pull requests merged in 2024-05, with the labels that each got.

#968 Bugfix/956 fix forgot password link
  lib/core/constants/urls.dart
  lib/core/services/remote_config_service.dart
  lib/ui/views/login_view.dart
  test/ui/views/login_view_test.dart
  test/ui/views/schedule_default_view_test.dart
Labels: size: S, version: Patch

#929 Feature/export to native calendar
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/MainActivity.kt
  android/build.gradle
  ios/Podfile.lock
  ios/Runner/Info.plist
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/utils/calendar_utils.dart
  lib/ui/views/schedule_view.dart
  lib/ui/widgets/calendar_selector.dart
  pubspec.lock
  pubspec.yaml
  test/ui/views/goldenFiles/scheduleView_1.png
  test/ui/views/goldenFiles/scheduleView_2.png
  test/ui/views/goldenFiles/scheduleView_3.png
  test/ui/views/goldenFiles/scheduleView_4.png
  test/ui/views/goldenFiles/scheduleView_5.png
Labels: enhancement, feature: Schedule, priority: medium, size: L, version: Minor

#908 Fix schedule cards not showing the correct end time
  lib/ui/widgets/schedule_calendar_tile.dart
  pubspec.yaml
Labels: size: XS, version: Patch

#921 Add weighted grade in evaluation tile
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/ui/views/grade_details_view.dart
  lib/ui/widgets/grade_evaluation_tile.dart
  pubspec.lock
  pubspec.yaml
  test/ui/widgets/grade_evaluation_tile_test.dart
Labels: platform: ios, platform: android, feature: Grades, size: S, version: Minor

#980 Update versions
  .github/workflows/dev-workflow.yaml
  .github/workflows/release-workflow.yaml
  README.fr.md
  README.md
  android/app/build.gradle
  pubspec.lock
  pubspec.yaml
Labels: size: M, version: Patch

#985 Fix sur iOS
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  pubspec.yaml
Labels: size: M, version: Minor

#979 Petites modifications visuelles
  l10n/intl_en.arb
  lib/ui/utils/app_theme.dart
  lib/ui/views/dashboard_view.dart
  lib/ui/widgets/dismissible_card.dart
  lib/ui/widgets/grade_button.dart
  lib/ui/widgets/schedule_settings.dart
  lib/ui/widgets/web_link_card.dart
  test/ui/views/goldenFiles/dashboardView_appletsCard_1.png
  test/ui/views/goldenFiles/dashboardView_progressBarCard_1.png
  test/ui/views/goldenFiles/dashboardView_scheduleCard_1.png
  test/ui/widgets/goldenFiles/scheduleSettingsView_1.png
  test/ui/widgets/schedule_settings_test.dart
Labels: size: M
