Repository ApplETS/Notre-Dame, pull requests merged in 2024-03, with the labels that each got.

#940 Light theme news details
  lib/ui/views/news_details_view.dart
  pubspec.yaml
Labels: size: S, version: Patch, hello

#936 Doc/document coding process rules
  .github/workflows/dev-workflow.yaml
  .github/workflows/devtools-workflow.yaml
  .github/workflows/master-workflow.yaml
  CONTRIBUTING.md
Labels: size: XS

#934 Hello - Handle different start/end date scenarios
  lib/core/managers/news_repository.dart
  lib/core/models/news.dart
  lib/ui/views/news_details_view.dart
  test/models/news_test.dart
  test/ui/views/ets_view_test.dart
  test/ui/views/goldenFiles/newsDetailsView_1.png
  test/ui/views/goldenFiles/newsView_2.png
  test/ui/views/news_details_view_test.dart
  test/ui/views/news_view_test.dart
  test/ui/widgets/news_card_test.dart
  test/viewmodels/news_details_viewmodel_test.dart
  test/viewmodels/news_viewmodel_test.dart
Labels: size: M, version: Patch

#937 [Hello] News infinite scroll
  .github/workflows/release-workflow.yaml
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/constants/quick_links.dart
  lib/core/managers/news_repository.dart
  lib/core/models/news.dart
  lib/core/services/launch_url_service.dart
  lib/core/viewmodels/news_details_viewmodel.dart
  lib/core/viewmodels/news_viewmodel.dart
  lib/locator.dart
  lib/ui/router.dart
  lib/ui/views/news_details_view.dart
  lib/ui/views/news_view.dart
  lib/ui/views/quick_links_view.dart
  lib/ui/views/schedule_view.dart
  lib/ui/widgets/news_card.dart
  pubspec.lock
  pubspec.yaml
  test/managers/news_repository_test.dart
  test/mock/managers/news_repository_mock.dart
  test/models/news_test.dart
  test/ui/views/ets_view_test.dart
  test/ui/views/goldenFiles/etsView_1.png
  test/ui/views/goldenFiles/newsView_1.png
  test/ui/views/goldenFiles/newsView_2.png
  test/ui/views/news_details_view_test.dart
  test/ui/views/news_view_test.dart
  test/ui/widgets/news_card_test.dart
  test/viewmodels/news_details_viewmodel_test.dart
  test/viewmodels/news_viewmodel_test.dart
Labels: size: XL, version: Minor

#899 Allow resizing schedule settings
  lib/ui/views/schedule_view.dart
  lib/ui/widgets/schedule_settings.dart
  pubspec.yaml
  test/ui/widgets/goldenFiles/scheduleSettingsView_1.png
  test/ui/widgets/schedule_settings_test.dart
Labels: size: M, version: Minor

#918 Add default schedules to the grades page
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/constants/router_paths.dart
  lib/core/managers/course_repository.dart
  lib/core/services/navigation_service.dart
  lib/core/viewmodels/dashboard_viewmodel.dart
  lib/core/viewmodels/login_viewmodel.dart
  lib/core/viewmodels/more_viewmodel.dart
  lib/core/viewmodels/schedule_default_viewmodel.dart
  lib/core/viewmodels/schedule_settings_viewmodel.dart
  lib/ui/router.dart
  lib/ui/views/grades_view.dart
  lib/ui/views/schedule_default_view.dart
  lib/ui/widgets/schedule_default.dart
  pubspec.yaml
  test/mock/managers/cache_manager_mock.dart
  test/mock/managers/course_repository_mock.dart
  test/mock/managers/quick_links_repository_mock.dart
  test/mock/managers/settings_manager_mock.dart
  test/mock/managers/user_repository_mock.dart
  test/mock/services/analytics_service_mock.dart
  test/mock/services/app_widget_service_mock.dart
  test/mock/services/flutter_secure_storage_mock.dart
  test/mock/services/github_api_mock.dart
  test/mock/services/home_widget_mock.dart
  test/mock/services/in_app_review_service_mock.dart
  test/mock/services/internal_info_service_mock.dart
  test/mock/services/launch_url_service_mock.dart
  test/mock/services/navigation_service_mock.dart
  test/mock/services/networking_service_mock.dart
  test/mock/services/preferences_service_mock.dart
  test/mock/services/remote_config_service_mock.dart
  test/mock/services/rive_animation_service_mock.dart
  test/mock/services/siren_flutter_service_mock.dart
  test/ui/views/faq_view_test.dart
  test/ui/views/goldenFiles/gradesView_2.png
  test/ui/views/goldenFiles/scheduleDefaultView_1.png
  test/ui/views/goldenFiles/scheduleDefaultView_2.png
  test/ui/views/grades_view_test.dart
  test/ui/views/not_found_view_test.dart
  test/ui/views/schedule_default_view_test.dart
  test/ui/widgets/schedule_default_test.dart
  test/viewmodels/schedule_default_viewmodel_test.dart
Labels: platform: ios, platform: android, feature: Schedule, size: L, version: Minor

#933 Hello - Author view
  assets/images/discord_logo.svg
  assets/images/email_logo.svg
  assets/images/facebook_logo.svg
  assets/images/instagram_logo.svg
  assets/images/linkedin_logo.svg
  assets/images/reddit_logo.svg
  assets/images/tiktok_logo.svg
  assets/images/x_logo.svg
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/constants/router_paths.dart
  lib/core/managers/author_repository.dart
  lib/core/models/author.dart
  lib/core/models/socialLink.dart
  lib/core/utils/utils.dart
  lib/core/viewmodels/author_viewmodel.dart
  lib/locator.dart
  lib/ui/router.dart
  lib/ui/utils/app_theme.dart
  lib/ui/views/author_view.dart
  lib/ui/views/news_details_view.dart
  lib/ui/widgets/author_info_skeleton.dart
  lib/ui/widgets/news_card.dart
  lib/ui/widgets/social_links_card.dart
  pubspec.lock
  pubspec.yaml
  test/helpers.dart
  test/managers/author_repository_test.dart
  test/mock/managers/author_repository_mock.dart
  test/ui/views/author_view_test.dart
  test/ui/views/ets_view_test.dart
  test/ui/views/goldenFiles/authorView_1.png
  test/ui/views/goldenFiles/authorView_2.png
  test/ui/views/goldenFiles/etsView_1.png
  test/ui/views/goldenFiles/newsView_1.png
  test/ui/views/goldenFiles/newsView_2.png
  test/ui/views/news_details_view_test.dart
  test/ui/views/news_view_test.dart
  test/ui/widgets/author_info_skeleton_test.dart
  test/ui/widgets/news_card_test.dart
  test/viewmodels/author_viewmodel_test.dart
  test/viewmodels/news_details_viewmodel_test.dart
  test/viewmodels/news_viewmodel_test.dart
Labels: size: XL, version: Minor

#953 Hello/feature/share export
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/ca/etsmtl/applets/etsmobile/MainActivity.kt
  android/build.gradle
  assets/images/report.svg
  ios/Podfile.lock
  ios/Runner/Info.plist
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/core/utils/calendar_utils.dart
  lib/core/viewmodels/calendar_selection_viewmodel.dart
  lib/ui/views/news_details_view.dart
  lib/ui/views/schedule_view.dart
  lib/ui/widgets/calendar_selector.dart
  lib/ui/widgets/report_news.dart
  pubspec.lock
  pubspec.yaml
  test/ui/views/goldenFiles/scheduleView_1.png
  test/ui/views/goldenFiles/scheduleView_2.png
  test/ui/views/goldenFiles/scheduleView_3.png
  test/ui/views/goldenFiles/scheduleView_4.png
  test/ui/views/goldenFiles/scheduleView_5.png
Labels: size: L, version: Minor, hello

#958 Update Podfile.lock
  ios/Podfile.lock
  pubspec.yaml
Labels: size: S, version: Patch
