Repository ApplETS/Notre-Dame, pull requests merged in 2024-06, with the labels that each got.

#987 Changes to accomodate multiple course reviews for a single course
  ios/Podfile.lock
  lib/core/managers/course_repository.dart
  lib/core/viewmodels/dashboard_viewmodel.dart
  lib/ui/views/grade_details_view.dart
  lib/ui/widgets/grade_button.dart
  pubspec.yaml
  test/managers/course_repository_test.dart
  test/ui/views/grades_details_view_test.dart
Labels: feature: Grades, size: M, version: Patch

#984 Landscape mode fixes
  lib/ui/utils/app_theme.dart
  lib/ui/views/contributors_view.dart
  lib/ui/views/grade_details_view.dart
  lib/ui/views/more_view.dart
  lib/ui/views/quick_links_view.dart
  lib/ui/views/schedule_view.dart
  lib/ui/views/settings_view.dart
  lib/ui/views/student_view.dart
  lib/ui/widgets/base_scaffold.dart
  lib/ui/widgets/navigation_rail.dart
  test/ui/views/goldenFiles/newsDetailsView_1.png
  test/ui/widgets/base_scaffold_test.dart
Labels: size: L, version: Minor

#978 Check for empty sessions list when getting course activities
  ios/Podfile.lock
  lib/core/managers/course_repository.dart
  pubspec.lock
  pubspec.yaml
  test/ui/views/goldenFiles/newsDetailsView_1.png
Labels: bug, feature: Schedule, size: XS, version: Patch

#977 Prevent s.o. semesters schedule from loading forever
  lib/core/constants/semester_codes.dart
  lib/core/managers/course_repository.dart
  lib/core/viewmodels/grades_viewmodel.dart
  pubspec.yaml
Labels: bug, feature: Schedule, size: XS, version: Patch
