Repository ApplETS/Notre-Dame, pull requests merged in 2025-01, with the labels that each got.

#1125 Adding AÉÉTS and 100 Génies quicklinks
  assets/images/ic_100genies_red.png
  assets/images/ic_aeets_red.png
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/features/ets/quick-link/models/quick_links.dart
  pubspec.yaml
Labels: feature: ÉTS, size: XS, version: Minor

#1129 Fixed empty schedule on sundays
  ios/Podfile.lock
  lib/features/schedule/schedule_default/schedule_default_viewmodel.dart
  pubspec.yaml
Labels: feature: Schedule, size: XS, version: Patch

#1128 Small color tweaks
  lib/features/student/grades/grade_details/grade_details_view.dart
  lib/utils/app_theme.dart
Labels: size: S, version: Patch
