Repository ApplETS/Notre-Dame, pull requests merged in 2025-05, with the labels that each got.

#1188 Check if the active course reviews are completed instead of all course reviews
  lib/data/services/signets-api/models/course.dart
  test/ui/student/grades/grade_details/widgets/grades_details_view_test.dart
Labels: size: S, version: Patch

#1190 Redesign navigation bar
  lib/data/models/navigation_menu_callback.dart
  lib/data/services/navigation_history_observer.dart
  lib/data/services/navigation_service.dart
  lib/domain/constants/router_paths.dart
  lib/main.dart
  lib/router.dart
  lib/ui/core/ui/base_navigation_bar.dart
  lib/ui/core/ui/base_scaffold.dart
  lib/ui/core/ui/bottom_bar.dart
  lib/ui/core/ui/navigation_menu/navigation_menu.dart
  lib/ui/core/ui/navigation_menu/navigation_menu_button.dart
  lib/ui/core/ui/navigation_rail.dart
  lib/ui/core/ui/root_view.dart
  lib/ui/core/ui/scaffold_safe_area.dart
  lib/ui/dashboard/widgets/dashboard_view.dart
  lib/ui/dashboard/widgets/grades_card.dart
  lib/ui/dashboard/widgets/schedule_card.dart
  lib/ui/ets/events/author/widgets/author_view.dart
  lib/ui/ets/events/news_details/widgets/news_details_view.dart
  lib/ui/ets/quick_links/security_info/widgets/emergency_view.dart
  lib/ui/ets/quick_links/security_info/widgets/security_view.dart
  lib/ui/ets/widgets/ets_view.dart
  lib/ui/more/contributors/widgets/contributors_view.dart
  lib/ui/more/faq/widgets/faq_view.dart
  lib/ui/more/settings/widgets/settings_view.dart
  lib/ui/more/view_model/more_viewmodel.dart
  lib/ui/not_found/view_model/not_found_viewmodel.dart
  lib/ui/schedule/widgets/calendars/day_calendar.dart
  lib/ui/schedule/widgets/schedule_view.dart
  lib/ui/startup/view_model/startup_viewmodel.dart
  lib/ui/student/grades/grade_details/widgets/grade_details_view.dart
  lib/ui/student/grades/widgets/grades_view.dart
  lib/ui/student/profile/widgets/profile_view.dart
  lib/ui/student/session_schedule/widgets/session_schedule_view.dart
  lib/ui/student/widgets/student_view.dart
  lib/utils/loading.dart
  test/ui/core/ui/base_scaffold_test.dart
  test/ui/core/ui/bottom_bar_test.dart
  test/ui/core/ui/navigation_menu/navigation_menu_button_test.dart
  test/ui/core/ui/navigation_menu/navigation_menu_test.dart
  test/ui/core/ui/root_view_test.dart
  test/ui/more/view_model/more_viewmodel_test.dart
  test/ui/not_found/view_model/not_found_viewmodel_test.dart
  test/ui/startup/view_model/startup_viewmodel_test.dart
Labels: size: XL

#1184 Init grades at N/A instead of 0%
  lib/data/services/signets-api/models/course_summary.dart
  lib/ui/student/grades/grade_details/widgets/grade_details_view.dart
  lib/ui/student/grades/widgets/grade_button.dart
  lib/ui/student/grades/widgets/grade_evaluation_tile.dart
  lib/utils/utils.dart
  test/ui/student/grades/grade_details/widgets/grades_details_view_test.dart
  test/ui/student/grades/widgets/grade_button_test.dart
  test/ui/student/grades/widgets/grade_evaluation_tile_test.dart
Labels: size: M, version: Patch

#1192 Remove todoes
  lib/data/repositories/user_repository.dart
  lib/ui/startup/view_model/startup_viewmodel.dart
  test/data/mocks/repositories/user_repository_mock.dart
  test/data/repositories/user_repository_test.dart
  test/ui/more/view_model/more_viewmodel_test.dart
  test/ui/startup/view_model/startup_viewmodel_test.dart
Labels: size: M

#1193 Internship programs shouldn't be the default
  ios/Podfile.lock
  lib/ui/student/profile/view_model/profile_viewmodel.dart
  lib/ui/student/profile/widgets/profile_view.dart
  pubspec.yaml
  test/ui/student/profile/view_model/profile_viewmodel_test.dart
  test/ui/student/profile/widgets/profile_view_test.dart
Labels: size: M, version: Patch

#1197 Issue-1191-correction
  lib/ui/dashboard/widgets/schedule_card.dart
  pubspec.yaml
Labels: size: XS, dart, version: Patch

#1204 Fix safe area of navigation menu
  lib/ui/core/ui/navigation_menu/navigation_menu.dart
  lib/ui/core/ui/root_view.dart
Labels: size: XS

#1209 internship portal, eportfolio and egrants quicklinks
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/data/models/quick_links.dart
  pubspec.yaml
Labels: size: S, version: Minor

#1202 Remove carousel_slider package
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/ui/core/themes/app_colors_extension.dart
  lib/ui/core/themes/app_theme.dart
  lib/ui/core/ui/carousel.dart
  lib/ui/core/ui/need_help_notice_dialog.dart
  lib/ui/more/faq/models/faq.dart
  lib/ui/more/faq/models/faq_actions.dart
  lib/ui/more/faq/models/faq_questions.dart
  lib/ui/more/faq/view_model/faq_viewmodel.dart
  lib/ui/more/faq/widgets/action_card.dart
  lib/ui/more/faq/widgets/faq_view.dart
  lib/ui/more/faq/widgets/question_card.dart
  pubspec.lock
  pubspec.yaml
  test/ui/more/faq/widgets/faq_view_test.dart
Labels: size: L, version: Patch

#1227 Ci/redo ios project
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
Labels: size: M

#1230 Remove mailto: from ApplETS's email address
  lib/domain/constants/app_info.dart
  lib/domain/constants/urls.dart
  lib/ui/more/faq/view_model/faq_viewmodel.dart
  lib/ui/more/faq/widgets/faq_view.dart
Labels: size: XS, version: Patch
