Repository ApplETS/Notre-Dame, pull requests merged in 2025-07, with the labels that each got.

#1260 Feature/#1210 background layout home page v5
  lib/ui/core/ui/root_view.dart
  lib/ui/dashboard/clipper/circle_clipper.dart
  lib/ui/dashboard/view/dashboard_view.dart
  lib/ui/dashboard/view_model/dashboard_viewmodel.dart
  lib/ui/dashboard/widgets/progression_card.dart
  lib/ui/dashboard/widgets/widget_component.dart
  pubspec.yaml
  test/ui/core/ui/root_view_test.dart
Labels: size: M, size: L, version: Minor

#1267 Dependency updates
  .github/workflows/dev-workflow.yaml
  .github/workflows/master-workflow.yaml
  .github/workflows/release-workflow.yaml
  android/build.gradle
  android/settings.gradle
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  pubspec.lock
  pubspec.yaml
Labels: size: M, version: Patch

#1269 Update v5
  .github/workflows/dev-workflow.yaml
  .github/workflows/master-workflow.yaml
  .github/workflows/release-workflow.yaml
  android/build.gradle
  android/settings.gradle
  assets/images/cafe_sans_filtre_logo.png
  assets/images/centre_sportif_logo.png
  assets/images/nimbus_logo.png
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  ios/fastlane/Matchfile
  lib/data/models/quick_links.dart
  lib/l10n/intl_en.arb
  lib/l10n/intl_fr.arb
  pubspec.lock
  pubspec.yaml
Labels: size: L

#1236 Merge events happening at the same time
  lib/data/models/activity_code.dart
  lib/data/repositories/course_repository.dart
  lib/data/services/calendar_service.dart
  lib/data/services/signets-api/commands/get_courses_activities_command.dart
  lib/data/services/signets-api/models/course_activity.dart
  lib/data/services/signets-api/models/schedule_activity.dart
  lib/ui/dashboard/view_model/dashboard_viewmodel.dart
  lib/ui/dashboard/widgets/course_activity_tile.dart
  lib/ui/dashboard/widgets/schedule_card.dart
  lib/ui/schedule/view_model/calendars/calendar_viewmodel.dart
  lib/ui/schedule/view_model/calendars/day_viewmodel.dart
  lib/ui/schedule/widgets/calendars/day_calendar.dart
  lib/ui/schedule/widgets/calendars/week_calendar.dart
  lib/ui/schedule/widgets/schedule_calendar_tile.dart
  lib/ui/student/session_schedule/view_model/session_schedule_viewmodel.dart
  lib/ui/student/session_schedule/widgets/session_schedule.dart
  pubspec.lock
  pubspec.yaml
  test/data/repositories/course_repository_test.dart
  test/data/services/signets_api/signets_api_client_test.dart
  test/ui/dashboard/view_model/dashboard_viewmodel_test.dart
  test/ui/dashboard/widgets/course_activity_tile_test.dart
  test/ui/dashboard/widgets/schedule_card_test.dart
  test/ui/more/view_model/more_viewmodel_test.dart
  test/ui/schedule/view_model/calendar/calendar_viewmodel_test.dart
  test/ui/schedule/view_model/calendar/week_viewmodel_test.dart
  test/ui/schedule/view_model/schedule_settings_viewmodel_test.dart
  test/ui/schedule/widgets/calendars/day_view_test.dart
  test/ui/schedule/widgets/calendars/month_view_test.dart
  test/ui/schedule/widgets/calendars/week_view_test.dart
  test/ui/schedule/widgets/schedule_settings_test.dart
  test/ui/student/session_schedule/view_model/schedule_default_viewmodel_test.dart
Labels: size: M, version: Minor
