Repository ApplETS/Notre-Dame, pull requests merged in 2025-06, with the labels that each got.

#1241 Fix crash in security view
  assets/images/emergency_meeting_points_dark.svg
  assets/images/emergency_meeting_points_light.svg
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/AppDelegate.swift
  lib/domain/constants/markers.dart
  lib/ui/ets/quick_links/security_info/view_model/security_viewmodel.dart
  lib/ui/ets/quick_links/security_info/widgets/security_view.dart
  pubspec.lock
  pubspec.yaml
  test/ui/ets/quick_links/security-info/widgets/security_view_test.dart
Labels: size: M, release/patch

#1242 Fix build ios
  ios/Podfile
  ios/Podfile.lock
  lib/data/services/launch_url_service.dart
  pubspec.lock
  pubspec.yaml
Labels: size: M, version: Patch

#1249 Translucent gesture bar
  lib/ui/startup/widgets/startup_view.dart
  pubspec.yaml
Labels: bug, size: S, size: XS, version: Patch

#1258 Feature/#1243 add quick links
  assets/images/cafe_sans_filtre_logo.png
  assets/images/centre_sportif_logo.png
  assets/images/nimbus_logo.png
  lib/data/models/quick_links.dart
  lib/l10n/intl_en.arb
  lib/l10n/intl_fr.arb
  pubspec.yaml
Labels: enhancement, feature: ÉTS, size: S, version: Minor

#1264 Fix ios build
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  ios/fastlane/Matchfile
  pubspec.yaml
Labels: size: S, size: M
