Repository ApplETS/Notre-Dame, pull requests merged in 2025-04, with the labels that each got.

#1178 Add permission internet to BrowserTabActivity
  android/app/src/main/AndroidManifest.xml
  pubspec.yaml
Labels: size: XS

#1180 Fix CI
  .github/composite/ci-build/action.yaml
  .github/workflows/release-workflow.yaml
  pubspec.yaml
Labels: size: XS

#1179 When a course is dropped, the grade button for that course is not displayed
  lib/ui/dashboard/view_model/dashboard_viewmodel.dart
  lib/ui/dashboard/widgets/grades_card.dart
  test/ui/dashboard/view_model/dashboard_viewmodel_test.dart
Labels: feature: Dashboard, size: S, version: Minor

#1181 Remove changelog
  .github/workflows/release-workflow.yaml
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/Info.plist
Labels: size: M

#1183 Fix appbar color in session schedule
  lib/ui/student/session_schedule/widgets/session_schedule.dart
  pubspec.yaml
Labels: size: S, version: Patch

#1182 Correctif swipe vue semaine
  ios/Podfile.lock
  lib/ui/schedule/view_model/calendars/week_viewmodel.dart
  lib/ui/schedule/widgets/calendars/week_calendar.dart
Labels: size: XS, version: Patch
