Repository ApplETS/Notre-Dame, pull requests merged in 2025-03, with the labels that each got.

#1141 Refactor schedule
  ios/Podfile.lock
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/router.dart
  lib/ui/core/themes/app_theme.dart
  lib/ui/core/ui/calendar_selector.dart
  lib/ui/ets/events/news_details/view_model/calendar_selection_viewmodel.dart
  lib/ui/ets/events/news_details/widgets/news_details_view.dart
  lib/ui/schedule/view_model/calendars/calendar_viewmodel.dart
  lib/ui/schedule/view_model/calendars/day_viewmodel.dart
  lib/ui/schedule/view_model/calendars/month_viewmodel.dart
  lib/ui/schedule/view_model/calendars/week_viewmodel.dart
  lib/ui/schedule/view_model/schedule_settings_viewmodel.dart
  lib/ui/schedule/view_model/schedule_viewmodel.dart
  lib/ui/schedule/widgets/calendars/calendar_controller.dart
  lib/ui/schedule/widgets/calendars/day_calendar.dart
  lib/ui/schedule/widgets/calendars/month_calendar.dart
  lib/ui/schedule/widgets/calendars/week_calendar.dart
  lib/ui/schedule/widgets/schedule_settings.dart
  lib/ui/schedule/widgets/schedule_view.dart
  lib/ui/student/session_schedule/view_model/session_schedule_viewmodel.dart
  lib/ui/student/session_schedule/widgets/session_schedule.dart
  lib/ui/student/session_schedule/widgets/session_schedule_view.dart
  lib/utils/utils.dart
  test/ui/schedule/view_model/calendar/calendar_viewmodel_test.dart
  test/ui/schedule/view_model/calendar/day_viewmodel_test.dart
  test/ui/schedule/view_model/calendar/month_viewmodel_test.dart
  test/ui/schedule/view_model/calendar/week_viewmodel_test.dart
  test/ui/schedule/view_model/schedule_viewmodel_test.dart
  test/ui/schedule/widgets/calendars/day_view_test.dart
  test/ui/schedule/widgets/calendars/month_view_test.dart
  test/ui/schedule/widgets/calendars/week_view_test.dart
  test/ui/schedule/widgets/schedule_calendar_tile_test.dart
  test/ui/schedule/widgets/schedule_settings_test.dart
  test/ui/schedule/widgets/schedule_view_test.dart
  test/ui/student/session_schedule/view_model/schedule_default_viewmodel_test.dart
  test/ui/student/session_schedule/widgets/schedule_default_test.dart
  test/ui/student/session_schedule/widgets/schedule_default_view_test.dart
Labels: size: XL, version: Patch

#1146 Fix unit tests
  lib/ui/schedule/view_model/calendars/calendar_viewmodel.dart
  lib/ui/schedule/view_model/calendars/week_viewmodel.dart
  lib/utils/utils.dart
  pubspec.yaml
  test/ui/schedule/widgets/calendars/week_view_test.dart
Labels: size: S, version: Patch

#1144 Feature/#1142 create tooltips
  ios/Podfile.lock
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/ui/dashboard/widgets/dashboard_view.dart
  lib/ui/ets/events/author/widgets/author_info_skeleton.dart
  lib/ui/ets/events/author/widgets/author_view.dart
  lib/ui/ets/events/news_details/widgets/news_details_view.dart
  lib/ui/ets/events/report_news/widgets/report_news_widget.dart
  lib/ui/ets/events/social/widgets/social_links_card.dart
  lib/ui/ets/quick_links/widgets/quick_links_view.dart
  lib/ui/login/widgets/password_text_field.dart
  lib/ui/login/widgets/universal_code_text_field.dart
  lib/ui/more/about/widgets/about_view.dart
  lib/ui/outage/widgets/outage_social_section.dart
  lib/ui/schedule/widgets/schedule_view.dart
  lib/ui/student/grades/grade_details/widgets/grade_details_view.dart
  lib/ui/student/grades/widgets/grades_view.dart
  lib/ui/student/session_schedule/widgets/session_schedule_view.dart
  pubspec.lock
  test/ui/more/about/widgets/about_view_test.dart
Labels: size: M, version: Minor

#1156 Bug/#1155 week viewmodel test
  pubspec.yaml
  test/ui/schedule/view_model/calendar/week_viewmodel_test.dart
Labels: bug, size: S, version: Patch

#1145 Fix animations dependencies
  lib/ui/ets/events/author/widgets/author_info_skeleton.dart
  lib/ui/ets/events/news/widgets/news_card.dart
  lib/ui/ets/events/news/widgets/news_card_skeleton.dart
  lib/ui/ets/events/news_details/widgets/news_details_view.dart
  lib/ui/student/grades/widgets/grades_view.dart
  pubspec.lock
  pubspec.yaml
  test/ui/ets/events/author/widgets/author_info_skeleton_test.dart
  test/ui/ets/events/news/widgets/news_skeleton_test.dart
Labels: bug, size: M, version: Minor

#1163 Upgrade to flutter 3.29
  .github/composite/flutter-setup/action.yaml
  ios/Podfile.lock
  pubspec.lock
  pubspec.yaml
Labels: size: M

#1057 Need help notice
  android/gradle/wrapper/gradle-wrapper.properties
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/ui/core/ui/need_help_notice_dialog.dart
  lib/ui/login/widgets/forgot_password.dart
  lib/ui/more/faq/view_model/faq_viewmodel.dart
  lib/ui/more/faq/widgets/faq_view.dart
  pubspec.lock
  test/ui/core/ui/need_help_notice_dialog_test.dart
  test/ui/more/faq/view_model/faq_viewmodel_test.dart
  test/ui/more/faq/widgets/faq_view_test.dart
Labels: size: M, version: Minor

#1162 Small color corrections
  lib/ui/core/themes/app_theme.dart
  lib/ui/schedule/widgets/schedule_settings.dart
  lib/ui/student/grades/widgets/grades_view.dart
Labels: size: S

#1147 Use controllers to update schedule settings in real time and return to today when pressing schedule in navbar
  lib/router.dart
  lib/ui/core/ui/base_navigation_bar.dart
  lib/ui/schedule/schedule_controller.dart
  lib/ui/schedule/view_model/schedule_settings_viewmodel.dart
  lib/ui/schedule/widgets/calendars/calendar_controller.dart
  lib/ui/schedule/widgets/calendars/day_calendar.dart
  lib/ui/schedule/widgets/calendars/month_calendar.dart
  lib/ui/schedule/widgets/calendars/week_calendar.dart
  lib/ui/schedule/widgets/schedule_settings.dart
  lib/ui/schedule/widgets/schedule_view.dart
  test/ui/core/ui/bottom_bar_test.dart
  test/ui/schedule/view_model/schedule_settings_viewmodel_test.dart
  test/ui/schedule/widgets/calendars/day_view_test.dart
  test/ui/schedule/widgets/calendars/month_view_test.dart
  test/ui/schedule/widgets/calendars/week_view_test.dart
  test/ui/schedule/widgets/schedule_settings_test.dart
  test/ui/schedule/widgets/schedule_view_test.dart
Labels: size: M, version: Patch

#1168 Refactor faq_view
  lib/ui/more/faq/widgets/action_card.dart
  lib/ui/more/faq/widgets/faq_view.dart
  lib/ui/more/faq/widgets/question_card.dart
  pubspec.yaml
Labels: size: M, version: Patch

#1165 Refactor dashboard view
  lib/data/models/broadcast_message.dart
  lib/data/repositories/broadcast_message_repository.dart
  lib/domain/broadcast_icon_type.dart
  lib/locator.dart
  lib/ui/dashboard/view_model/dashboard_viewmodel.dart
  lib/ui/dashboard/widgets/about_us_card.dart
  lib/ui/dashboard/widgets/broadcast_message_card.dart
  lib/ui/dashboard/widgets/dashboard_view.dart
  lib/ui/dashboard/widgets/grades_card.dart
  lib/ui/dashboard/widgets/progress_bar_card.dart
  lib/ui/dashboard/widgets/schedule_card.dart
  test/data/mocks/repositories/broadcast_message_repository_mock.dart
  test/helpers.dart
  test/ui/core/ui/need_help_notice_dialog_test.dart
  test/ui/dashboard/view_model/dashboard_viewmodel_test.dart
  test/ui/dashboard/widgets/about_us_card_test.dart
  test/ui/dashboard/widgets/dashboard_view_test.dart
  test/ui/dashboard/widgets/grades_card_test.dart
  test/ui/dashboard/widgets/progress_bar_card_test.dart
  test/ui/dashboard/widgets/schedule_card_test.dart
  test/ui/ets/events/author/widgets/author_view_test.dart
  test/ui/ets/events/news/view_model/news_viewmodel_test.dart
  test/ui/ets/events/news/widgets/news_view_test.dart
  test/ui/ets/quick_links/view_model/web_link_card_viewmodel_test.dart
  test/ui/ets/widgets/ets_view_test.dart
  test/ui/login/widgets/login_view_test.dart
  test/ui/more/faq/view_model/faq_viewmodel_test.dart
  test/ui/more/faq/widgets/faq_view_test.dart
  test/ui/more/settings/view_model/choose_language_viewmodel_test.dart
  test/ui/more/settings/view_model/settings_viewmodel_test.dart
  test/ui/more/settings/widgets/choose_language_view_test.dart
  test/ui/more/settings/widgets/settings_view_test.dart
  test/ui/more/view_model/more_viewmodel_test.dart
  test/ui/more/widgets/more_view_test.dart
  test/ui/schedule/view_model/calendar/calendar_viewmodel_test.dart
  test/ui/schedule/view_model/calendar/day_viewmodel_test.dart
  test/ui/schedule/view_model/calendar/month_viewmodel_test.dart
  test/ui/schedule/view_model/calendar/week_viewmodel_test.dart
  test/ui/schedule/view_model/schedule_settings_viewmodel_test.dart
  test/ui/schedule/widgets/calendars/day_view_test.dart
  test/ui/schedule/widgets/calendars/month_view_test.dart
  test/ui/schedule/widgets/calendars/week_view_test.dart
  test/ui/schedule/widgets/schedule_settings_test.dart
  test/ui/schedule/widgets/schedule_view_test.dart
  test/ui/startup/view_model/startup_viewmodel_test.dart
  test/ui/student/grades/grade_details/view_model/grades_details_viewmodel_test.dart
  test/ui/student/grades/grade_details/widgets/grades_details_view_test.dart
  test/ui/student/grades/view_model/grades_viewmodel_test.dart
  test/ui/student/grades/widgets/grades_view_test.dart
  test/ui/student/widgets/student_view_test.dart
Labels: size: XL

#1170 Bugfix/fix reset password link
  .gitignore
  l10n/intl_en.arb
  l10n/intl_fr.arb
  lib/ui/more/faq/view_model/faq_viewmodel.dart
  lib/ui/more/faq/widgets/faq_view.dart
  test/ui/more/faq/view_model/faq_viewmodel_test.dart
  test/ui/more/faq/widgets/faq_view_test.dart
Labels: size: XS
